#ifndef NETSDK_H
#define NETSDK_H

#include "NetClientTypes.h"

int  LoadNVSSDK();
void FreeNVSSDK();

int NetClient_Startup_V4(int _iServerPort, int _iClientPort, int _iWnd);
int NetClient_SetNotifyFunction_V4(MAIN_NOTIFY_V4        _MainNotify, 
		ALARM_NOTIFY_V4       _AlarmNotify,
		PARACHANGE_NOTIFY_V4  _ParaNotify,
		COMRECV_NOTIFY_V4     _ComNotify,
		PROXY_NOTIFY       _ProxyNotify);
int NetClient_StartRecv_V4(unsigned int* _uiRecvID, CLIENTINFO* _cltInfo, NVSDATA_NOTIFY _cbkDataArrive,void* _iUserData);
int NetClient_StartRecv_V5(unsigned int* _puiRecvID, NetClientPara* _ptPara, int _iParaSize);
int NetClient_SetNotifyUserData_V4(int _iLogonID,void* _iUserData);
int NetClient_SetComRecvNotify_V4(COMRECV_NOTIFY_V4 _comNotify);
int NetClient_GetHTTPPort_V4(int _iLogonID, int* _iPort);
int NetClient_SetHTTPPort_V4(int _iLogonID, int _iPort);
int NetClient_SetDomainParsePara_V4(int _iLogonID, int _iInterval, char* _cUserID, char* _cPassword, char* _cHost, char* _cDomain1, char* _cDomain2,int _iPort1, int _iPort2);
int NetClient_GetDomainParsePara_V4(int _iLogonID, int* _iInterval, char* _cUserID, char* _cPassword, char* _cHost, char* _cDomain1, char* _cDomain2,int* _iPort1, int* _iPort2);
int NetClient_GetBitrateOnVideo_V4(unsigned int _ulConID, int* _piX, int* _piY, int* _piEnabled, char* _pcInfo);
int NetClient_SetDecCallBack_V4(unsigned int _ulConID, DECYUV_NOTIFY_V4 _cbkDecYUV, void* _iUserData);
int NetClient_RegisterDrawFun(unsigned int _ulConID, CBK_DRAW_FUNC _pfDrawFun, long _lUserData, void* _pCmd, int _iCmdLen);
int NetClient_SetPort( int _iServerPort, int _iClientPort );
#ifdef WIN32
int NetClient_Startup();
int NetClient_SetNotifyFunction( LOGON_NOTIFY _LogonNotify,ALARM_NOTIFY _AlarmNotify, PARACHANGE_NOTIFY _ParaNotify);
int NetClient_SetNotifyFunctionEx( MAIN_NOTIFY _cbkMainNotify, ALARM_NOTIFY_EX _cbkAlarmNotify, PARACHANGE_NOTIFY_EX _cbkParaChangeNotify, void* _pNotifyUserData );
int NetClient_SetMSGHandle( unsigned int _uiMessage, HWND _hWnd, unsigned int _uiParaMsg, unsigned int _uiAlarmMsg );
int NetClient_SetMSGHandleEx( unsigned int _uiMessage, HWND _hWnd, unsigned int _uiParaMsg, unsigned int _uiAlarmMsg );
int NetClient_StartRecv(unsigned int* _ulConID, CLIENTINFO* _cltInfo, RECVDATA_NOTIFY _cbkDataArrive);
int NetClient_StartRecvEx(unsigned int* _ulConID,CLIENTINFO* _cltInfo,RECVDATA_NOTIFY_EX _cbkDataNotifyEx, void* _lpUserData);
int NetClient_SetComRecvNotify(COMRECV_NOTIFY _comNotify);
int NetClient_GetHTTPPort(int _iLogonID, unsigned short* _iPort);
int NetClient_SetHTTPPort(int _iLogonID, unsigned short _iPort);
int NetClient_SetDomainParsePara(int _iLogonID, int _iInterval, char* _cUserID, char* _cPassword, char* _cHost, char* _cDomain1, char* _cDomain2,unsigned short _iPort1, unsigned short _iPort2);
int NetClient_GetDomainParsePara(int _iLogonID, int* _iInterval, char* _cUserID, char* _cPassword, char* _cHost, char* _cDomain1, char* _cDomain2,unsigned short* _iPort1, unsigned short* _iPort2);
int NetClient_GetBitrateOnVideo(unsigned int _ulConID, int* _iX, int* _iY, int* _iEnabled);
int NetClient_SetDecCallBack(unsigned int _ulConID, DECYUV_NOTIFY _cbkGetYUV, void* _pContext);
int NetClient_InterTalkStartEx(unsigned int * _uiConnID, int _iLogonID, RECVDATA_NOTIFY_EX _cbkDataArrive, void* _iUserData);
#else
int NetClient_Startup(int _iServerPort/*=3000*/, int _iClientPort/*=6000*/, int _iWnd/*=0*/);
int NetClient_SetNotifyFunction(MAIN_NOTIFY_V4        _MainNotify, 
										  ALARM_NOTIFY_V4       _AlarmNotify,
										  PARACHANGE_NOTIFY_V4  _ParaNotify,
										  COMRECV_NOTIFY_V4     _ComNotify,
										  PROXY_NOTIFY       _ProxyNotify);
int NetClient_StartRecv(unsigned int* _uiRecvID, CLIENTINFO* _cltInfo, NVSDATA_NOTIFY _cbkDataArrive,void* _iUserData);
int NetClient_SetNotifyUserData(int _iLogonID,void* _iUserData);
int NetClient_SetComRecvNotify(COMRECV_NOTIFY_V4 _comNotify);
int NetClient_GetHTTPPort(int _iLogonID, int* _iPort);
int NetClient_SetHTTPPort(int _iLogonID, int _iPort);
int NetClient_SetDomainParsePara(int _iLogonID, int _iInterval, char* _cUserID, char* _cPassword, char* _cHost, char* _cDomain1, char* _cDomain2,int _iPort1, int _iPort2);
int NetClient_GetDomainParsePara(int _iLogonID, int* _iInterval, char* _cUserID, char* _cPassword, char* _cHost, char* _cDomain1, char* _cDomain2,int* _iPort1, int* _iPort2);
int NetClient_GetBitrateOnVideo(unsigned int _ulConID, int* _piX, int* _piY, int* _piEnabled, char* _pcInfo);
int NetClient_SetDecCallBack(unsigned int _ulID, pfCBGetDecAV _cbkGetYUV, void* _iUserData);
int NetClient_SetDecCallBackEx(unsigned int _ulID, DECYUV_NOTIFY _cbkDecYUV, void* _iUserData);
int NetClient_InterTalkStartEx(unsigned int * _uiConnID, int _iLogonID, NVSDATA_NOTIFY _cbkDataArrive, void* _iUserData);
#endif
int NetClient_Cleanup();
int NetClient_GetVersion(SDK_VERSION* _ver);
int NetClient_Logon(char* _cProxy,char* _cIP,char* _cUserName,
					char* _cPwd,char* _cProductID,int _iPort);
int NetClient_LogonEx(char* _cProxy,char* _cIP,char* _cUserName,
							  char* _cPwd,char* _cProductID,int _iPort,const char* _pcCharSet);
int NetClient_Logoff(int _iLogonID);
int NetClient_GetLogonStatus(int _iLogonID);
int NetClient_ProxyGetDevInfo(int _iLogonID, int _iCmd, void* _pvOutBuf, int _iBufLen);
int NetClient_StopRecv(unsigned int _uiRecvID);
int NetClient_GetRecvID(int _iLogonID, int _iChannel, int _iStreamNO);
int NetClient_GetInfoByConnectID(unsigned int _iConnectID,st_ConnectInfo* _stConnectInfo);
int NetClient_SetFullStreamNotify (unsigned int _uiRecvID, FULLFRAME_NOTIFY _cbkFullStream);
int NetClient_SetFullStreamNotify_V4 (unsigned int _uiRecvID, FULLFRAME_NOTIFY_V4 _cbkFullStream, void * _iUserData);
int NetClient_GetCmdString(int _iLogonID,int _iType,int _iPara,CMDSTRING_NOTIFY _cbkCmdString,void* _pUserData);
int NetClient_GetDevInfo(int _iLogonID,ENCODERINFO* _pEncoderInfo);
int NetClient_SendDataToServer(int _iLogonID,char* _cData,int _iLen);
int NetClient_IsValidUser(int _iLogonID,char* _cUserName,char* _cPwd);
int NetClient_SetInnerDataNotify(unsigned int _uiRecvID,INNER_DATA_NOTIFY _cbkNotify,void* _iUserData);
int NetClient_SetWorkMode(int _iWorkMode);
#ifdef WIN32
int NetClient_AddActiveServer(char* _cDevIP,char* _cFactoryID,void* _iSocket, void* _pUserData);
int NetClient_BindSocket(int _iLogonID,int _iChan,void* _iSocket, void* _pUserData);
#else
int NetClient_AddActiveServer(char* _cDevIP,char* _cFactoryID,int _iSocket, void* _pUserData);
int NetClient_BindSocket(int _iLogonID,int _iChan,int _iSocket, void* _pUserData);
#endif
int NetClient_PushData(int _iLogonID,int _iChan,char* _cData,int _iLen);
int NetClient_DelActiveServer(int _iLogonID);
int NetClient_StartCaptureData(unsigned long _ulID);
int NetClient_StopCaptureData(unsigned long _ulID);
int NetClient_GetVideoHeader(unsigned long _ulID,unsigned char* _ucHeader);
int NetClient_SetRawFrameCallBack(unsigned int _ulConID, RAWFRAME_NOTIFY _cbkGetFrame, void* _pContext);
int NetClient_SetRawFrameCallBackEx(unsigned int _ulConID, RAWFRAME_NOTIFY_EX _cbkGetFrame, void* _pContext);
int NetClient_StartCaptureFile(unsigned int _uiRecvID, char* _pszFileName, int _iRecordFileType);
int NetClient_StopCaptureFile(unsigned int _uiRecvID);
int NetClient_GetCaptureStatus(unsigned int _ulConID);
int NetClient_SetCaptureFileSize(unsigned int _uiRecvID, int _iFileSize);
int NetClient_StartPlay(unsigned int _ulID, int _hWnd, RECT _rcShow, unsigned int _uiDecflag);
int NetClient_StartPlayEx(unsigned int _ulID, void* _pvBuff, int _iBuffSize);
int NetClient_StartPlayEs(unsigned int _ulID, int _hWnd);
int NetClient_StopPlay(unsigned int _ulID);
int NetClient_StopPlayEx(unsigned int _ulID, unsigned int _iParam);
int NetClient_SetPlayRectEx(unsigned int _ulID, RECT* _pDrawRect, int _dwMask);
int NetClient_SetSrcRect(unsigned int _ulID, void* _pSrcRect);
int NetClient_ResetPlayerWnd(unsigned int _ulID, int _hwnd);
int NetClient_GetPlayingStatus(unsigned int _ulID);
int NetClient_AdjustVideo(unsigned int _ulID, RECT _rctShow);
int NetClient_AudioStart(unsigned int _ulID);
int NetClient_AudioStop(unsigned int _ulID);
int NetClient_SetLocalAudioVolume(int _iVolume);
int NetClient_SetBufferNum(unsigned int _ulID, int _iNum);
int NetClient_SetPlayDelay(unsigned long _ulID, int _iNum);
int NetClient_GetChannelNum(int _iLogonID, int* _piChanNum);
int NetClient_GetAlarmPortNum(int _iLogonID, int* _iAlarmInPortNum, int* _iAlarmOutPortNum);
int NetClient_GetLocalAlarmNum(int _iLogonID, int* _iLocalAlarmInNum, int* _iLocalAlarmOutNum);
int NetClient_SetVideoPara(int _iLogonID, int _iChannelNum, STR_VideoParam* _strVideoParam);
int NetClient_GetVideoPara(int _iLogonID, int _iChannelNum, STR_VideoParam* _strVideoParam);
int NetClient_SetVideoparaSchedule(int _iLogonID, int _iChannelNum,STR_VideoParam* _strVideoParam[MAX_TIMESEGMENT]);
int NetClient_GetVideoparaSchedule(int _iLogonID, int _iChannelNum,STR_VideoParam* _strVideoParam[MAX_TIMESEGMENT]);
int NetClient_SetVideoQuality(int _iLogonID, int _iChannelNum, int _iVideoQuality, int _iStreamNO);
int NetClient_GetVideoQuality(int _iLogonID,int _iChannelNum,int* _iVideoQuality, int _iStreamNO);
int NetClient_SetFrameRate(int _iLogonID, int _iChannelNum, int _iFrameRate, int _iStreamNO);
int NetClient_GetFrameRate(int _iLogonID, int _iChannelNum, int* _iFrameRate, int _iStreamNO);
int NetClient_GetDecordFrameNum (unsigned int _ulConID);
int NetClient_SetStreamType(int _iLogonID, int _iChannelNum, int _iStreamType, int _iStreamNO);
int NetClient_GetStreamType(int _iLogonID, int _iChannelNum, int* _iStreamType, int _iStreamNO);
int NetClient_SetMotionAreaEnable (int _iLogonID,int _iChannelNum);
int NetClient_SetMotionDetetionArea(int _iLogonID, int _iChannelNum, int _ix, int _iy,int _iEnabled);
int NetClient_GetMotionDetetionArea(int _iLogonID, int _iChannelNum, int _ix, int _iy,int* _iEnabled);
int NetClient_SetThreshold(int _iLogonID, int _iChannelNum,int _iThreshold);
int NetClient_GetThreshold(int _iLogonID, int _iChannelNum,int* _iThreshold);
int NetClient_SetMotionDetection(int _iLogonID, int _iChannelNum,int _iEnabled);
int NetClient_GetMotionDetection(int _iLogonID, int _iChannelNum,int* _iEnabled);
int NetClient_SetMotionDecLinkRec(int _iLogonID,int _iChannelNum,int _iEnable);
int NetClient_GetMotionDecLinkRec(int _iLogonID,int _iChannelNum,int* _iEnable);
int NetClient_SetMotionDecLinkSnap(int _iLogonID,int _iChannelNum,int _iEnable);
int NetClient_GetMotionDecLinkSnap(int _iLogonID,int _iChannelNum,int* _iEnable);
int NetClient_SetMotionDecLinkSoundDisplay(int _iLogonID,int _iChannelNum,int _iSoundEnable,int _iDisplayEnable);
int NetClient_GetMotionDecLinkSoundDisplay(int _iLogonID,int _iChannelNum,int* _iSoundEnable,int* _iDisplayEnable);
int NetClient_SetMotionDecLinkOutport(int _iLogonID,int _iChannelNum,int _iOutportArray);
int NetClient_GetMotionDecLinkOutport(int _iLogonID,int _iChannelNum,int* _iOutportArray);
int NetClient_SetMotionDetectSchedule(int _iLogonID,int _iChannelNum,int _iWeekday,PNVS_SCHEDTIME _strScheduleParam[MAX_TIMESEGMENT]);
int NetClient_GetMotionDetectSchedule(int _iLogonID,int _iChannelNum,int _iWeekday,PNVS_SCHEDTIME _strScheduleParam[MAX_TIMESEGMENT]);
int NetClient_SetOsdDiaphaneity(int _iLogonID,int _iChannelNum,int _iDiaphaneity);
int NetClient_GetOsdDiaphaneity(int _iLogonID,int _iChannelNum,int* _iDiaphaneity);
int NetClient_SetOsdText(int _iLogonID, int _iChannelNum, unsigned char * _pcTxtPtr, unsigned long _ulTextColor);
int NetClient_GetOsdText(int _iLogonID, int _iChannelNum, unsigned char* _pcOSDText, unsigned long* _pulTextColor);
int NetClient_SetOsdType(int _iLogonID, int _iChannelNum,int _iPositionX,int _iPositionY,int _iOSDType,int _iEnabled);
int NetClient_GetOsdType(int _iLogonID, int _iChannelNum, int _iOSDType, int* _iPositionX ,int* _iPositionY , int* _iEnabled);
int NetClient_SetDateFormat(int _iLogonID, int _iFormat, char _cSeparate);
int NetClient_GetDateFormat(int _iLogonID, int* _iFormat, char* _cSeparate);
int NetClient_SetOsdLOGO (int _iLogonID, int _iChannelNum, unsigned char * _cLogoFile, unsigned int _ulbkColor);
int NetClient_SetAudioChannel(int _iLogonID, int _iChannelNum, int _iAudioChannel);
int NetClient_GetAudioChannel(int _iLogonID, int _iChannelNum, int* _iAudioChannel);
int NetClient_SetIpFilter(int _iLogonID, char* _cFilterIP,char* _cFilterMask);
int NetClient_GetIpFilter(int _iLogonID, char* _cFilterIP,char* _cFilterMask);
int NetClient_SetAlarmOutput(int _iLogonID, int _iAlarmInput, unsigned long _ulAlarmOutput);
int NetClient_GetAlarmOutput(int _iLogonID, int _iAlarmInput, unsigned long* _ulAlarmOutput);
int NetClient_GetAlarmIPortState(int _iLogonID, int _iInPort,int* _iState);
int NetClient_SetAlarmPortEnable(int _iLogonID,int _iInPort,int _iEnabled);
int NetClient_GetAlarmPortEnable(int _iLogonID,int _iInPort,int* _iEnabled);
int NetClient_SetInportAlarmLinkRec(int _iLogonID,int _iPortNo,int _iEnable);
int NetClient_GetInportAlarmLinkRec(int _iLogonID,int _iPortNo,int* _iEnable);
int NetClient_SetInportAlarmLinkSnap(int _iLogonID,int _iPortNo,int _iEnable);
int NetClient_GetInportAlarmLinkSnap(int _iLogonID,int _iPortNo,int* _iEnable);
int NetClient_SetInportAlarmLinkPTZ(int _iLogonID,int _iPortNo,int _iLinkChannelNum,int _iLinkType,int _iActNum);
int NetClient_GetInportAlarmLinkPTZ(int _iLogonID,int _iPortNo,int _iLinkChannelNum,int* _iLinkType,int* _iActNum);
int NetClient_SetInportAlarmLinkSoundDisplay(int _iLogonID,int _iPortNo,int _iSoundEnable,int _iDisplayEnable);
int NetClient_GetInportAlarmLinkSoundDisplay(int _iLogonID,int _iPortNo,int* _iSoundEnable,int* _iDisplayEnable);
int NetClient_SetInportAlmLinkOutport(int _iLogonID,int _iPortNo,int _iOutportArray);
int NetClient_GetInportAlmLinkOutport(int _iLogonID,int _iPortNo,int* _iOutportArray);
int NetClient_SetAlarmInMode(int _iLogonID, int _iPortNum, int _iLowOrHigh);
int NetClient_GetAlarmInMode(int _iLogonID, int _iPortNum, int* _iLowOrHigh);
int NetClient_SetAlarmOutMode(int _iLogonID, int _iPortNum, int _iLowOrHigh, int _iPulseWidth);
int NetClient_GetAlarmOutMode(int _iLogonID, int _iPortNum, int* _iLowOrHigh, int* _iPulseWidth);
int NetClient_SetInportAlarmSchedule(int _iLogonID,int _iPortNo,int _iWeekday,PNVS_SCHEDTIME _strScheduleParam[MAX_TIMESEGMENT]);
int NetClient_GetInportAlarmSchedule(int _iLogonID,int _iPortNo,int _iWeekday,PNVS_SCHEDTIME _strScheduleParam[MAX_TIMESEGMENT]);
int NetClient_SetOutportAlarmSchedule(int _iLogonID,int _iPortNo,int _iWeekday,PNVS_SCHEDTIME _strScheduleParam[MAX_TIMESEGMENT]);
int NetClient_GetOutportAlarmSchedule(int _iLogonID,int _iPortNo,int _iWeekday,PNVS_SCHEDTIME _strScheduleParam[MAX_TIMESEGMENT]);
int NetClient_SetOutportAlarmDelay(int _iLogonID,int _iPortNo,int _iClearType,int _iDelayTime);
int NetClient_GetOutportAlarmDelay(int _iLogonID,int _iPortNo,int* _iClearType,int* _iDelayTime);
int NetClient_SetInportEnable(int _iLogonID, int _iPortNo,int _iEnable);
int NetClient_GetInportEnable(int _iLogonID, int _iPortNo,int* _iEnable);
int NetClient_SetOutportEnable(int _iLogonID, int _iPortNo,int _iEnable);
int NetClient_GetOutportEnable(int _iLogonID, int _iPortNo,int* _iEnable);
int NetClient_SetOutportState(int _iLogonID, int _iPort, int _iState);
int NetClient_GetOutportState(int _iLogonID, int _iPort, int* _iState);
int NetClient_SetAlmVdoCovThreshold(int _iLogonID, int _iChannelNum, int _iThreshold);
int NetClient_GetAlmVdoCovThreshold(int _iLogonID, int _iChannelNum, int* _iThreshold);
int NetClient_SetAlmVideoCov(int _iLogonID, int _iChannelNum, int _iEnabled);
int NetClient_GetAlmVideoCov(int _iLogonID, int _iChannelNum, int* _iEnabled);
int NetClient_SetDeviceType(int _iLogonID,int _iChannelNum,int _iComNo,int _iDevAddress,const char* _pcProtocol);
int NetClient_GetDeviceType(int _iLogonID,int _iChannelNum,int* _iComPort,int* _iDevAddress ,char* _cDeviceType);
int NetClient_SetComFormat(int _iLogonID,int _iComPort,char* _cDeviceType,char* _cComFormat,int _iWorkMode);
int NetClient_GetComFormat(int _iLogonID, int _iCom, char* _cComFormat,int* _iWorkMode);
int NetClient_GetAllSupportDeviceType(int _iLogonID, int* _iSumDeviceType, char* _cDeviceType);
int NetClient_DeviceCtrl(int _iLogonID, int _iChannelNum,int _iActionType, int _iParam1,int _iParam2);
int NetClient_DeviceCtrlEx(int _iLogonID,int _iChannelNum,int _iActionType,int _iParam1,int _iParam2,int _iControlType);
int NetClient_ComSend(int _iLogonID, unsigned char* _ucBuf, int _iLength, int _iComNo);
int NetClient_DevicePTZCtrl(int _iLogonID, int _iProtocolType, int _iActionType, int _iComNo, int _iAddress, int _iSpeed, int _iPresetNO);
int NetClient_GetComPortCounts(int _iLogonID, int* _piComPortCounts, int* _piComPortEnabledStatus);
int NetClient_SetAlarmVideoLost(int _iLogonID, int _iChannelNum,int _iEnabled);
int NetClient_GetAlarmVideoLost(int _iLogonID, int _iChannelNum, int* _iEnabled);
int NetClient_SetVideoLostLinkPTZ(int _iLogonID,int _iChannelNum,int _iLinkChannelNum,int _iLinkType,int _iActNum);
int NetClient_GetVideoLostLinkPTZ(int _iLogonID,int _iChannelNum,int _iLinkChannelNum,int* _iLinkType,int* _iActNum);
int NetClient_SetVideoLostLinkSoundDisplay(int _iLogonID,int _iChannelNum,int _iSoundEnable,int _iDisplayEnable );
int NetClient_GetVideoLostLinkSoundDisplay(int _iLogonID,int _iChannelNum,int* _iSoundEnable,int* _iDisplayEnable);
int NetClient_GetAlarmVLostState(int _iLogonID, int _iChannel,int* _iState);
int NetClient_SetVideoLostLinkOutport(int _iLogonID,int _iChannelNum,int _iOutportArray);
int NetClient_GetVideoLostLinkOutport(int _iLogonID,int _iChannelNum,int* _iOutportArray);
int NetClient_SetVideoLostSchedule(int _iLogonID,int _iChannelNum,int _iWeekday,PNVS_SCHEDTIME _strScheduleParam[MAX_TIMESEGMENT]);
int NetClient_GetVideoLostSchedule(int _iLogonID,int _iChannelNum,int _iWeekday,PNVS_SCHEDTIME _strScheduleParam[MAX_TIMESEGMENT]);
int NetClient_SetVideoLostLinkRec(int _iLogonID,int _iChannelNum,int _iEnable);
int NetClient_GetVideoLostLinkRec(int _iLogonID,int _iChannelNum,int* _iEnable);
int NetClient_SetVideoLostLinkSnap(int _iLogonID,int _iChannelNum,int _iEnable);
int NetClient_GetVideoLostLinkSnap(int _iLogonID,int _iChannelNum,int* _iEnable);
int NetClient_SetIFrameRate(int _iLogonID, int _iChannelNum, int _iFrameRate, int _iStreamNO);
int NetClient_GetIFrameRate(int _iLogonID, int _iChannelNum, int* _iFrameRate, int _iStreamNO);
int NetClient_ForceIFrame(int _iLogonID, int _iChannelNum, int _iStreamNO);
int NetClient_SetTime(int _iLogonID, int _iyy, int _imo, int _idd, int _ihh, int _imi, int _iss);
int NetClient_Reboot(int _iLogonID);
int NetClient_RebootEx(int _iLogonID, int _iChannelNo);
int NetClient_DefaultPara(int _iLogonID);
int NetClient_DefaultParaEx(int _iLogonID, int _iType);
int NetClient_GetServerVersion(int _iLogonID, char* _cVer);
int NetClient_SetNVS(int _iLogonID, int _iVideo, int _iCheck);
int NetClient_UpgradeProgram(int _iLogonID, char* _cFileName, PROUPGRADE_NOTIFY _UpgradeNotify);
int NetClient_UpgradeWebPage(int _iLogonID, char* _cFileName, WEBUPGRADE_NOTIFY _UpgradeWebNotify);
int NetClient_GetUpgradePercent(int _iLogonID);
int NetClient_GetUserNum(int _iLogonID,int* _iUserNum);
int NetClient_GetUserInfo(int _iLogonID,int _iUserSerial,char* _cUserName,char* _cPassword,int* _iAuthority);
int NetClient_GetCurUserInfo(int _iLogonID, char _cUserName[16], char _cPassword[16], int* _iAuthority);
int NetClient_AddUser(int _iLogonID, char* _cUserName, char* _cPassword, int _iAuthority);
int NetClient_DelUser(int _iLogonID, char* _cUserName);
int NetClient_ModifyPwd(int _iLogonID, char* _cUserName, char* _cNewPwd);
int NetClient_SetMaxConUser(int _iLogonID, int _iMaxConUser);
int NetClient_GetMaxGetUser(int _iLogonID,int* _iMaxConUser);
int NetClient_TalkStart(int _iLogonID, int _iUser);
int NetClient_TalkEnd(int _iLogonID);
int NetClient_InputTalkingdata(unsigned char* _ucData, unsigned int _iLen);
int NetClient_GetTalkingState(int _iLogonID,int* _iTalkState);
int NetClient_CapturePic(unsigned int _ulConID,unsigned char** _pucData);
int NetClient_CaptureBmpPic(unsigned int _ulConID, char* _pcFileName);
int NetClient_ChangeSvrIP(int _iLogonID, char* _cNewSvrIP, char* _cMask, char* _cGateway, char* _cDNS);
int NetClient_GetIpProperty(int _iLogonID, char* _cMAC, char* _cMask, char* _cGateway, char* _cDNS);
int NetClient_SetDHCPParam(int _iLogonID,int _iDHCP);
int NetClient_GetDHCPParam(int _iLogonID,int* _iDHCP);
int NetClient_SetWifiDHCPParam(int _iLogonID,int _iDHCP);
int NetClient_GetWifiDHCPParam(int _iLogonID,int* _iDHCP);
int NetClient_GetVideoCovArea(int _iLogonID, int _iChannelNum, RECT* _rect, int _iStreamNO);
int NetClient_SetVideoCovArea(int _iLogonID, int _iChannelNum, RECT* _rect, int _iStreamNO);
int NetClient_GetVideoSize(int _iLogonID, int _iChannelNum, int* _width, int * _height, int _iStreamNO);
int NetClient_SetVideoSize(int _iLogonID, int _iChannelNum, int _iVideoSize, int _iStreamNO);
int NetClient_GetVideoSizeEx(int _iLogonID, int _iChannelNum, int* _ivideoSize, int _iStreamNO);
int NetClient_GetMaxMinorVideoSize(int _iLogonID, int* _iMinorVideoSize);
int NetClient_BindInterface(int _interface);
char* NetClient_GetNetInterface(int _interface);
int NetClient_SetMaxKByteRate(int _iLogonID, int _iChannelNum, int _ibitRate, int _iStreamNO);
int NetClient_GetMaxKByteRate(int _iLogonID, int _iChannelNum, int* _ibitRate, int _iStreamNO);
int NetClient_WriteUserData(int _iLogonID,int _iOffset,unsigned char* _u8Buf,int _iLength);
int NetClient_ReadUserData(int _iLogonID,int _iOffset,unsigned char* _u8Buf,int _iLength);
int NetClient_SetReducenoiseState(int _iLogonID, int _iChannelNum,int _iState);
int NetClient_GetReducenoiseState(int _iLogonID,int _iChannelNum,int* _iState);
int NetClient_DrawTextOnVideo(int _iLogonID, int _iChannelNum, int _iX, int _iY, char* _cText, int _iStore, int _iStreamNO);
int NetClient_GetTextOnVideo(int _iLogonID, int _iChannelNum, int* _iX, int* _iY, char* _cText,int _iStreamNO);
int NetClient_SetBothStreamSame(int _iLogonID, int _iChannelNum, int _iState);
int NetClient_GetBothStreamSame(int _iLogonID, int _iChannelNum, int* _iState);
int NetClient_ShowBitrateOnVideo(unsigned int _ulConID, int _iX, int _iY, int _iEnabled);
int NetClient_SetPPPoEInfo(int _iLogonID,char* _cAccount, char* _cPassword, int _iEnabled);
int NetClient_GetPPPoEInfo(int _iLogonID,char* _cAccount, char* _cPassword, int* _iEnabled);
int NetClient_CPUCheckEnabled(int _iEnabled, int _interval);
int NetClient_SetEncodeMode(int _iLogonID, int _iChannelNum, int _iStreamNO, int _iMode);
int NetClient_GetEncodeMode(int _iLogonID, int _iChannelNum, int _iStreamNO, int* _iMode);
int NetClient_SetPreferMode(int _iLogonID, int _iChannelNum, int _iStreamNO, int _iMode);
int NetClient_GetPreferMode(int _iLogonID, int _iChannelNum, int _iStreamNO, int* _iMode);
int NetClient_LogFileSetProperty(int _iLogonID, int _iLevel, int _iSize);
int NetClient_LogFileGetProperty(int _iLogonID, int* _iLevel, int* _iSize);
int NetClient_LogFileDownload(int _iLogonID);
int NetClient_LogFileClear(int _iLogonID);
int NetClient_LogFileGetDetails(int _iLogonID, char* _cBuf, int* _iLen);
int NetClient_GetVideoNPMode(int _iLogonID, VIDEO_NORM* _vMode);
int NetClient_SetVideoNPMode(int _iLogonID, VIDEO_NORM _vMode);
int NetClient_SetAudioEncoder(int _iLogonID, int _iChannel, AUDIO_ENCODER _aCoder);
int NetClient_GetAudioEncoder(int _iLogonID, int _iChannel, AUDIO_ENCODER* _aCoder);
int NetClient_NetFileQuery(int _iLogonID, PNVS_FILE_QUERY _ptFileQuery);
int NetClient_NetFileSetRecordRule(int _iLogonID, int _iRule, int _iTimelen, int _iFreedisk ,int _iFileSize);
int NetClient_NetFileGetRecordRule(int _iLogonID, int* _iRule, int* _iTimelen, int* _iFreedisk,int* _iFileSize);
int NetClient_NetFileSetAlarmRule(int _iLogonID, int _iPreRecordEnable, int _iPreRecordTime, int _iDelayTime ,int _iDelayEnable ,int _iChannelNum);
int NetClient_NetFileGetAlarmRule(int _iLogonID, int* _iPreEnable, int* _iPreTime, int* _iDelayTime ,int* _iDelayEnable,int _iChannelNum);
int NetClient_NetFileSetAlarmState(int _iLogonID, int _iChannel, int _iState);
int NetClient_NetFileGetAlarmState(int _iLogonID, int _iChannel, int* _iState);
int NetClient_NetFileSetTaskState(int _iLogonID, int _iChannel, int _iState);
int NetClient_NetFileGetTaskState(int _iLogonID, int _iChannel, int* _iState);
int NetClient_NetFileSetTaskSchedule(int _iLogonID, int _iChannel, int _iWeekday, NVS_SCHEDTIME* _Schedule[MAX_TIMESEGMENT]);
int NetClient_NetFileGetTaskSchedule(int _iLogonID, int _iChannel, int _iWeekday, NVS_SCHEDTIME* _Schedule[MAX_TIMESEGMENT]);
int NetClient_NetFileSetTaskScheduleEx(int _iLogonID, int _iChannel, int _iWeekday, NVS_SCHEDTIME_Ex* _Schedule[MAX_TIMESEGMENT]);
int NetClient_NetFileGetTaskScheduleEx(int _iLogonID, int _iChannel, int _iWeekday, NVS_SCHEDTIME_Ex* _Schedule[MAX_TIMESEGMENT]);
int NetClient_NetFileGetFileCount(int _iLogonID, int* _piTotalCount, int* _piCurrentCount);
int NetClient_NetFileRebuildIndexFile(int _iLogonID, int _iState);
int NetClient_NetFileGetDiskInfo(int _iLogonID, PNVS_STORAGEDEV _storage);
int NetClient_NetFileGetDiskInfoEx(int _iLogonID, PNVS_STORAGEDEV _storage, int _iSize);
int NetClient_NetFileIsSupportStorage(int _iLogonID);
int NetClient_NetFileDownloadFile(unsigned int* _ulID,
								  int _iLogonID, 
								  char* _cRemoteFilename, 
								  char* _cLocalFilename,
								  int _iFlag,
								  int _iPosition,
								  int _Speed);
int NetClient_NetFileDownloadFileEx(unsigned int* _ulConID,
									int _iLogonID, 
									char* _cRemoteFilename, 
									char* _cLocalFilename,
									int _iFlag,
									int _iPosition,
									int _Speed,
									NVSDATA_NOTIFY _cbkDataArrive,
									void* _iUserData);
int NetClient_NetFileStopDownloadFile(unsigned int _ulID);
int NetClient_NetFileGetDownloadPos(unsigned int _ulID, int* _iPos, int* _iDLSize);
int NetClient_NetFileMountUSB(int _iLogonID, int _iState);
int NetClient_NetFileGetRecordState(int _iLogonID, int _iChannel, RECORD_STATE* _piState);
int NetClient_NetFileDelFile(int _iLogonID,const char* _pcFileName);
int NetClient_DiskSetUsage(int _iLogonID,int _iDiskNo,int _iUsage);
int NetClient_NetFileGetQueryfile(int _iLogonID, int _iFileIndex, PNVS_FILE_DATA _fileInfo);
int NetClient_DiskFormat(int _iLogonID,int _iDiskNo,int _iFsType);
int NetClient_DiskPart(int _iLogonID,int _iDiskNo,int _iPartNum,int _iFormatNow);
int NetClient_NetFileManualRecord(int _iLogonID, int _iChannel, int _iState);
int NetClient_NetFileMapStoreDevice(int _iLogonID,PNVS_NFS_DEV _storeDev);
int NetClient_NetFileGetMapStoreDevice(int _iLogonID,PNVS_NFS_DEV _storeDev);
int NetClient_NetFileGetUSBstate(int _iLogonID, int* _iState);
int NetClient_NetFileSetExtendname(int _iLogonID, char* _cExtend);
int NetClient_NetFileGetExtendname(int _iLogonID, char* _cExtend);
int NetClient_ClearDisk(int _iLogonID,int _iDiskNo);
int NetClient_GetDownloadFailedFileName(int _iLogonID, int _iFileID, char* _pcFileName, int _iFileNameBufSize);
int NetClient_SetMediaStreamClient(int _iLogonID, int _iChannel, char* _cClientIP, unsigned short _iClientPort, int _iStreamType);
int NetClient_GetMediaStreamClient(int _iLogonID, int _iChannel, char* _cClientIP, unsigned short* _iClientPort, int* _iStreamType);
int NetClient_SetEmailAlarm(int _iLogonID, PSMTP_INFO _pSmtp);
int NetClient_GetEmailAlarm(int _iLogonID, PSMTP_INFO _pSmtp);
int NetClient_SetEmailAlarmEnable(int _iLogonID, int _iChannel, int _iEnable);
int NetClient_GetEmailAlarmEnable(int _iLogonID, int _iChannel, int* _iEnable);
int NetClient_SetScene(int _iLogonID, int _iChannel, int _iScene);
int NetClient_GetScene(int _iLogonID, int _iChannel, int* _iScene);
int NetClient_SetSensorFlip(int _iLogonID, int _iChannel, int _iFlip);
int NetClient_GetSensorFlip(int _iLogonID, int _iChannel, int* _iFlip);
int NetClient_SetSensorMirror(int _iLogonID, int _iChannel, int _iMirror);
int NetClient_GetSensorMirror(int _iLogonID, int _iChannel, int* _iMirror);
int NetClient_Snapshot(int _iLogonID, int _iChannel, int _iQvalue);
int NetClient_GetFactoryID(int _iLogonID, char* _cFactoryID);
int NetClient_SetWifiParam(int _iLogonID, NVS_WIFI_PARAM* _pWifiParam);
int NetClient_GetWifiParam(int _iLogonID, NVS_WIFI_PARAM* _pWifiParam);
int NetClient_WifiSearch(int _iLogonID);
int NetClient_GetWifiSearchResult(int _iLogonID, WIFI_INFO** _pWifiInfo, int* _iWifiCount);
int NetClient_SetPrivacyProtect(int _iLogonID,int _iChannelNum,int _iEnabled);
int NetClient_GetPrivacyProtect(int _iLogonID,int _iChannelNum,int* _iEnabled);
int NetClient_IYUVtoYV12(int _iWidth, int _iHeight, unsigned char* _YUV420);
int NetClient_GetDevType(int _iLogonID,int* _iDevType);
int NetClient_GetProductType(int _iLogonID,int* _iType);
int NetClient_GetProductTypeEx(int _iLogonID, int* _piProductMode, int* _piProductType);
int NetClient_BackupKernel(int _iLogonID);
int NetClient_SetUPNPEnable(int _iLogonID,int _iEnable);
int NetClient_GetUPNPEnable(int _iLogonID,int* _iEnable);
int NetClient_GetSysInfo(int _iLogonID);
int NetClient_SetDDNSPara(int _iLogonID,char* _cDUserName,char* _cDPassword,char* _cDNvsName, char* _cDomain,int _iPort,int _iDEnable);
int NetClient_GetDDNSPara(int _iLogonID,char* _cDUserName,char* _cDPassword,char* _cDNvsName, char* _cDomain,int* _iPort,int* _iDEnable);
int NetClient_SetFuncListArray(int _iLogonID,int _iEnableArray);
int NetClient_GetFuncListArray(int _iLogonID,int* _iEnableArray);
int NetClient_SendStringToServer(int _iLogonID, char* _cMsg, int _iLen);
int NetClient_ReceiveString(char* _cIpAddress,int* _iType,char* _cMsg,int* _iLen);
int NetClient_SendStringToCenter(char* _cIpAddress, int _iServerPort,char* _cMsg, int _iLen);
int NetClient_SetVencType(int _iLogonID,int _iChannelNum,int _iType);
int NetClient_GetVencType(int _iLogonID,int _iChannelNum,int* _iType);
int NetClient_SetComServer(int _iLogonID,char* _cComServer,int _iComServerPort);
int NetClient_GetComServer(int _iLogonID,char* _cComServer,int* _iComServerPort);
int NetClient_Get3GDeviceStatus(int _iLogonID, int* _i3GDeviceType,int* _iStatus,int* _iIntensity,char* _pcIP,char* _pcStarttime);
int NetClient_Set3GDialog(int _iLogonID, int _iStartType,int _iStopType,int _iDuration);
int NetClient_Get3GDialog(int _iLogonID, int* _iStartType,int* _iStopType,int* _iDuration);
int NetClient_Set3GMessage(int _iLogonID, char* _cNotify,char* _cPhoneNum1,char* _cPhoneNum2,char* _cPhoneNum3,char* _cPhoneNum4,char* _cPhoneNum5);
int NetClient_Get3GMessage(int _iLogonID, char* _cNotify,char* _cPhoneNum1,char* _cPhoneNum2,char* _cPhoneNum3,char* _cPhoneNum4,char* _cPhoneNum5);
int NetClient_Set3GTaskSchedule(int _iLogonID, int _iEnable, PNVS_SCHEDTIME _strScheduleParam);
int NetClient_Get3GTaskSchedule(int _iLogonID, int* _iEnable, PNVS_SCHEDTIME _strScheduleParam);
int NetClient_Set3GNotify(int _iLogonID, int _iType,char* _cMessage);
int NetClient_Get3GNotify(int _iLogonID, int* _iType,char* _cMessage);
int NetClient_SetHDCamer(int _iLogonID, int _iChannel,int _iFuncNum,int _iValue);
int NetClient_GetHDCamer(int _iLogonID, int _iChannel,int _iFuncNum,int* _iValue);
int NetClient_SetAlarmServer(int _iLogonID,const char* _pcAlarmServer,int _iServerPort);
int NetClient_GetAlarmServer(int _iLogonID,char* _pcAlarmServer,int* _iServerPort);
int NetClient_InterTalkStart(unsigned int * _uiConnID, int _iLogonID, int _iUserData );
int NetClient_InterTalkEnd(unsigned int _uiConnID, bool _blStopTalk);
int NetClient_NetFileQueryEx(int _iLogonID, PNVS_FILE_QUERY _pfileQuery, int _iSizeOfQuery);
int NetClient_ControlDeviceRecord(int _iLogonID, int _iChannelID, int _iRecordType, int _iAction);
int NetClient_NetFileDownloadByTimeSpan(unsigned int* _ulConID, int _iLogonID, char* _pcLocalFile, 
					int _iChannelNO, unsigned int _uiFromSecond, unsigned int _uiToSecond, 
                                                  int _iFlag, int _iPosition,int _iSpeed);
int NetClient_NetFileDownloadByTimeSpanEx( unsigned int* _ulConID, int _iLogonID, char* _pcLocalFile, 
					int _iChannelNO, NVS_FILE_TIME* _pTimeBegin, NVS_FILE_TIME* _pTimeEnd, 
                                                     int _iFlag, int _iPosition,int _iSpeed);
int NetClient_NetFileDownloadByTimeSpanCallBack( unsigned int* _ulConID, 
                                                 int _iLogonID, 
												 char* _pcLocalFile,
												 int _iChannelNO,
                                                 NVS_FILE_TIME* _pTimeBegin, 
                                                 NVS_FILE_TIME* _pTimeEnd, 
												 NVSDATA_NOTIFY _cbkDataArrive,
                                                 int _iFlag, 
                                                 int _iPosition,
                                                 int _iSpeed,
                                                 void* _iUserData);
int NetClient_NetLogQuery(int _iLogonID, PNVS_LOG_QUERY _logQuery);
int NetClient_NetLogGetLogfile(int _iLogonID, int _iLogIndex, PNVS_LOG_DATA _pLogInfo);
int NetClient_NetLogGetLogCount(int _iLogonID, int* _iTotalCount, int* _iCurrentCount);
int NetClient_GetProtocolList(int _iLogonID, st_NVSProtocol* _pstNVSProtocol);
int NetClient_SetCHNPTZCRUISE(int _iLogonID,int _iChannelNum,int _iCruiseNo,int _iEnable,int _iCruiseNum,st_PTZCruise* _stPTZCruise);
int NetClient_GetCHNPTZCRUISE(int _iLogonID,int _iChannelNum,int _iCruiseNo,int* _iEnable,int* _iCruiseNum,st_PTZCruise* _stPTZCruise);
int NetClient_SetVIDEOCOVER_LINKRECORD(int _iLogonID,int _iChannelNum,int _iEnableByBits);
int NetClient_GetVIDEOCOVER_LINKRECORD(int _iLogonID,int _iChannelNum,int* _iEnableByBits);
int NetClient_SetVIDEOCOVER_LINKPTZ(int _iLogonID,int _iChannelNum,int _iLinkChannel,int _iLinkType,int _iNo);
int NetClient_GetVIDEOCOVER_LINKPTZ(int _iLogonID,int _iChannelNum,int _iLinkChannel,int* _iLinkType,int* _iNo);
int NetClient_GetAlarmVCoverState(int _iLogonID, int _iChannel,int* _iState);
int NetClient_StopCaptureDate(unsigned long _ulID);
int NetClient_SetColorToGray(int _iLogonID,int _iChannelNum, int _iEnable);
int NetClient_GetColorToGray(int _iLogonID,int _iChannelNum, int* _iEnable);
int NetClient_SetCustomChannelName(int _iLogonID,int _iChannelNum,int _iChannelType, char* _cChannelName);
int NetClient_GetCustomChannelName(int _iLogonID,int _iChannelNum,int _iChannelType, char* _cChannelName);
int NetClient_SetCustomRecType(int _iLogonID,int _iRecType, char* _cRecTypeName);
int NetClient_GetCustomRecType(int _iLogonID,int _iRecType, char* _cRecTypeName);
int NetClient_ChangeSvrIPEx(int _iLogonID, char* _cNewSvrIP, char* _cMask, char* _cGateway, char* _cDNS, char* _cBackDNS);
int NetClient_GetIpPropertyEx(int _iLogonID,char* _cMAC, char* _cMask, char* _cGateway, char* _cDNS, char* _cBackDNS);
int NetClient_SetFTPUpdate(int _iLogonID,char* _cFtpAddr,char* _cFilePath,char* _cFtpUserName, char* _cFtpPassword);
int NetClient_GetFTPUpdate(int _iLogonID,char* _cFtpAddr,char* _cFilePath,char* _cFtpUserName, char* _cFtpPassword);
int NetClient_SetCHNPTZFormat(int _iLogonID,int _iChannelNum,char* _cComFormat);
int NetClient_GetCHNPTZFormat(int _iLogonID,int _iChannelNum,char* _cComFormat);
int NetClient_GetServerVersionEx(int _iLogonID, char* _cVer,char* _cUIVersion,char* _cSlaveVersion);
int NetClient_GetOSDTypeColor(int _iLogonID, int _iChannelNum, int _iOSDType, int* _iColor);
int NetClient_SetOSDTypeColor(int _iLogonID, int _iChannelNum, int _iOSDType, int _iColor);
int NetClient_GetExceptionMsg(int _iLogonID, int _iExceptionTyep, int* _iState);
int NetClient_SetNTPInfo(int _iLogonID, char* _NTPServer, unsigned short _iPort, int _iInterval);
int NetClient_GetNTPInfo(int _iLogonID, char* _NTPServer, unsigned short* _iPort, int* _iInterval);
int NetClient_SetVideoEncrypt(int _iLogonID, int _iChannel, void* _lpCmdBuf, int _iBufSize);
int NetClient_GetVideoEncrypt(int _iLogonID, int _iChannel, void* _lpCmdBuf, int _iBufSize);
int NetClient_SetVideoDecrypt(int _iLogonID, int _iChannel, void* _lpCmdBuf, int _iBufSize);
int NetClient_GetVideoDecrypt(int _iLogonID, int _iChannel, void* _lpCmdBuf, int _iBufSize);
int NetClient_SetPreRecEnable(int _iLogonID, int _iChannel, int _iEnable);
int NetClient_GetPreRecEnable(int _iLogonID, int _iChannel, int* _piEnable);
int NetClient_SetVideoCombine(int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_GetVideoCombine(int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_VCASetConfig(int _iLogonID, int _iVCACmdID, int _iChannel, void* _lpCmdBuf, int _iCmdBufLen);
int NetClient_VCAGetConfig(int _iLogonID, int _iVCACmdID, int _iChannel, void* _lpCmdBuf, int _iCmdBufLen);
int NetClient_VCARestart(int _iLogonID);
int NetClient_VCARestartEx(int _iLogonID, int _iChannelNO);
int NetClient_VCAGetAlarmInfo(int _iLogonID, int _iAlarmIndex, void* _lpBuf, int _iBufSize);
int NetClient_SetEmailAlarmEx(int _iLogonID, PSMTP_INFO _pSmtp, int _iSize);
int NetClient_GetEmailAlarmEx(int _iLogonID, PSMTP_INFO _pSmtp, int _iSize);
int NetClient_SetFTPUploadConfig(int _iLogonID, int _iCmd, void* _lpCmdBuf, int _iBufSize);
int NetClient_GetFTPUploadConfig(int _iLogonID, int _iCmd, void* _lpCmdBuf, int _iBufSize);
int NetClient_Set3GConfig(int _iLogonID, int _iCmd, int _iChannel, void* _lpValueBuf, int _iBufSize);
int NetClient_Get3GConfig(int _iLogonID, int _iCmd, int _iChannel, void* _lpValueBuf, int _iBufSize);
int NetClient_SetDigitalChannelConfig(int _iLogonID, int _iChannel, int _iCmd, void* _lpCmdBuf, int _iBufSize);
int NetClient_GetDigitalChannelConfig(int _iLogonID, int _iChannel, int _iCmd, void* _lpCmdBuf, int _iBufSize);
int NetClient_DigitalChannelSend(int _iLogonID, int _iChannel, unsigned char* _ucBuf, int _iLength);
int NetClient_SendComData(int _iLogonID, int _iCommand, void* _lpInBuffer, int _iInBufferSize);
int NetClient_SetVideoNPModeEx(int _iLogonID, int _iChannel, VIDEO_NORM _iNPMode);
int NetClient_GetVideoNPModeEx(int _iLogonID, int _iChannel, VIDEO_NORM* _piNPMode);
int NetClient_GetDigitalChannelNum(int _iLogonID, int* _piDigitChannelNum);
int NetClient_GetChannelProperty(int _iLogonID, int _iChannel, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_SetDeviceTimerReboot(int _iLogonID, int _iEnable, int _iInterval, int _iHour);
int NetClient_GetDeviceTimerReboot(int _iLogonID, int* _iEnable, int* _iInterval, int* _iHour);
int NetClient_SetVideoCoverSchedule(int _iLogonID, int _iChannel, int _iWeekday,PNVS_SCHEDTIME _strScheduleParam[MAX_TIMESEGMENT]);
int NetClient_GetVideoCoverSchedule(int _iLogonID, int _iChannel, int _iWeekday,PNVS_SCHEDTIME _strScheduleParam[MAX_TIMESEGMENT]);
int NetClient_SetCPUMEMAlarmThreshold(int _iLogonID, int _iCPUThreshold, int _iMEMThreshold);
int NetClient_GetCPUMEMAlarmThreshold(int _iLogonID, int* _iCPUThreshold, int* _iMEMThreshold);
int NetClient_SetDZInfo(int _iLogonID, DZ_INFO_PARAM* _pDZ_INFO);
int NetClient_GetDZInfo(int _iLogonID, DZ_INFO_PARAM* _pDZ_INFO);
int NetClient_SetPTZAutoBack(int _iLogonID, int _iChannel,int _iEnable,int _iPresetIndex,int _iIdleTime);
int NetClient_GetPTZAutoBack(int _iLogonID, int _iChannel,int* _iEnable,int* _iPresetIndex,int* _iIdleTime);
int NetClient_Set3GVPND(int _iLogonID, char* _cDialNumber,char* _cAccount,char* _cPassword);
int NetClient_Get3GVPND(int _iLogonID, char* _cDialNumber,char* _cAccount,char* _cPassword);
int NetClient_SetHDCamerEx(int _iLogonID, int _iChannel, int _iFuncID, void* _lpBuf, int _iSize);
int NetClient_GetHDCamerEx(int _iLogonID, int _iChannel, int _iFuncID, void* _lpBuf, int _iSize);
int NetClient_SetFTPUsage(int _iLogonID, char* _cFtpAddr, int _iPort, char* _cFilePath,char* _cFtpUserName, char* _cFtpPassword,int _iUsage);
int NetClient_GetFTPUsage(int _iLogonID, char* _cFtpAddr, int* _piPort, char* _cFilePath,char* _cFtpUserName, char* _cFtpPassword,int* _piUsage);
int NetClient_SetChannelSipConfig(int _iLogonID, int _iChannel, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_GetChannelSipConfig(int _iLogonID, int _iChannel, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_GetMaxVideoSize(int _iLogonID, int* _iVideoSize);
int NetClient_SetBitRatePercent(int _iLogonID, int _iChannelNO, int _iPercent);
int NetClient_GetBitRatePercent(int _iLogonID, int _iChannelNO, int* _piPercent);
int NetClient_GetVideoParam(unsigned int _uiConnID, int* _piWidth, int* _piHeight, int* _piFrameRate);
int NetClient_SetOSDAlpha(int _iLogonID, int _iChannel,int _iAlpha);
int NetClient_GetOSDAlpha(int _iLogonID, int _iChannel,int* _iAlpha);
int NetClient_DeviceSetup(int _iLogonID, int _iFlag,const char* _pcSection,const char* _pcKeyword,const char* _pcValue);
int NetClient_SetPlayerShowFrameMode(int _iLogonID,int _iChannelNum, unsigned int _uiShowFrameMode, int _iStreamNO);
int NetClient_GetPlayerShowFrameMode(int _iLogonID,int _iChannelNum,int _iStreamNO);
int NetClient_DrawRectOnLocalVideo(unsigned int _uiConID, RECT* _rcRect, int _iCount);
int NetClient_DrawPolyOnLocalVideo(unsigned int _uiConnID, POINT* _pPointArray, int _iPointCount, int _iFlag);
int NetClient_SendStringToServerEx(int _iLogonID,char* _cMsg,int _iLen, int _iFlag);
int NetClient_SetNetFileDownloadFileCallBack(unsigned int _ulConID, RECV_DOWNLOADDATA_NOTIFY _cbkDataNotify, void* _lpUserData);
int NetClient_SetDataPackCallBack(unsigned int _ulConID, int _iCBType, void* _pvCallBack, void* _pvUserData);
int NetClient_AddConnectionToNetWork(int _iSocket, void* _Connection, void* _NotifyFun);
void* NetClient_MallocConnection();
int NetClient_FreeConnection(void* _pConnect);
int NetClient_NetFileSetChannelParam(int _iLogonID,int _iChannelNo,int _iCmd, void* _lpBuf);
int NetClient_NetFileGetChannelParam(int _iLogonID,int _iChannelNo,int _iCmd, void* _lpBuf);
int NetClient_ShutDownDev(int _iLogonID, int _iFlag);
int NetClient_BackupImage(int _iLogonID , int _iType);
int NetClient_SetLanParam(int _iLogonID, int _iCmd, void* _lpData);
int NetClient_GetLanParam(int _iLogonID, int _iCmd, void* _lpData);
int NetClient_GetVideoSzList( int _iLogonID, int _iChannel, int _iStreamNo, int* _piList, int*  _piLstCount );
int NetClient_SetAlarmConfig( int _iLogonID, int _iChannel, int _iAlarmType, int _iCmd, void* _pvCmdBuf);
int NetClient_GetAlarmConfig(int _iLogonID, int _iChannel, int _iAlarmType, int _iCmd, void* _pvCmdBuf);
int NetClient_SetITSBlock(int _iLogonID, int _iBlockID, int _iX, int _iY);
int NetClient_GetITSBlock(int _iLogonID, int _iBlockID, int* _iX, int* _iY);
int NetClient_SetHDTimeRangeParam(int _iLogonID, int _iChannel, int _iIndex, void* _lpBuf, int _iBufSize);
int NetClient_GetHDTimeRangeParam(int _iLogonID, int _iChannel, int _iIndex, void* _lpBuf, int _iBufSize);
int NetClient_SetHDTemplateName(int _iLogonID, int _iTemplateID, char* _cTemplateName);
int NetClient_GetHDTemplateName(int _iLogonID, int _iTemplateID,char* _cTemplateName);
int NetClient_SetHDTemplateMap(int _iLogonID, int _iChannel, void* _lpBuf, int _iBufSize);
int NetClient_GetHDTemplateMap(int _iLogonID, int _iChannel, void* _lpBuf, int _iBufSize);
int NetClient_SetITSTimeRangeEnable(int _iLogonID, int _iChannel, int _iIndex, void* _lpBuf, int _iBufSize);
int NetClient_GetITSTimeRangeEnable(int _iLogonID, int _iChannel, int _iIndex, void* _lpBuf, int _iBufSize);
int NetClient_SetITSTimeRange(int _iLogonID, int _iIndex, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_GetITSTimeRange(int _iLogonID, int _iIndex, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_SetITSDetectMode(int _iLogonID, int _iMode);
int NetClient_GetITSDetectMode(int _iLogonID, int* _iMode);
int NetClient_SetITSLoopMode(int _iLogonID, int _iLoopMode);
int NetClient_GetITSLoopMode(int _iLogonID, int* _iLoopMode);
int NetClient_SetITSDeviceType(int _iLogonID, int _iDeviceType);
int NetClient_GetITSDeviceType(int _iLogonID, int* _iDeviceType);
int NetClient_SetITSRoadwayParam(int _iLogonID, int _iCmd, void * _lpBuf, int _iBufSize);
int NetClient_GetITSRoadwayParam(int _iLogonID, int _iCmd, void * _lpBuf, int _iBufSize);
int NetClient_SetITSLicensePlateOptimize(int _iLogonID, int _iCmd, void * _lpBuf, int _iBufSize);
int NetClient_GetITSLicensePlateOptimize(int _iLogonID, int _iCmd, void * _lpBuf, int _iBufSize);
int NetClient_SetITSExtraInfo(int _iLogonID, int _iCmd, int _iChannel, void* _pvCmdBuf, int _iCmdLen);
int NetClient_GetITSExtraInfo(int _iLogonID, int _iCmd, int _iChannel, void* _pvCmdBuf, int _iCmdLen);
int NetClient_CheckDeviceState(int _iLogonID, int _iChannelNo, int _iType);
int NetClient_GetDeviceState(int _iLogonID, int _iChannelNo, int _iType, int* _iValue);
int NetClient_GetCameraCheckInfo(int _iLogonID, int _iChannelNo, int _iType, int* _iValue);
int NetClient_CheckCamera(int _iLogonID, int _iChannelNo, int _iType, int _iEnable);
int NetClient_GetCharSet(int _iLogonID, char* _pcCharSet);
int NetClient_SetTimeZone(int _iLogonID, int _iTimeZone);
int NetClient_GetTimeZone(int _iLogonID, int* _iTimeZone);
int NetClient_SetCurLanguage(int _iLogonID, char* _pcLanguage);
int NetClient_GetCurLanguage(int _iLogonID, char* _pcLanguage);
int NetClient_GetLanguageList(int _iLogonID, st_NVSLanguageList* _pStrctLanguageList);
int NetClient_SetChannelEncodeProfile(int _iLogonID, int _iChannelNum, int _iStreamNo, int _iLevel);
int NetClient_GetChannelEncodeProfile(int _iLogonID, int _iChannelNum, int _iStreamNo, int* _piLevel);
int NetClient_SetAlarmClear(int _iLogonID, int _iChannelNo, int _iClearType);
int NetClient_SetExceptionHandleParam( int _iLogonID, int _iExceptionType, int _iFlag );
int NetClient_GetExceptionHandleParam( int _iLogonID, int _iExceptionType, int* _iFlag);
int NetClient_SetAlarmLink_V1(int _iLogonID, int _iChannelNo, int _iAlarmLinkType, void * _pParam, int _iParamSize );
int NetClient_GetAlarmLink_V1(int _iLogonID, int _iChannelNo, int _iAlarmLinkType, void * _pParam, int _iParamSize );
int NetClient_SetCameraParam(int _iLogonID, void * _lpBuf, int _iBufSize);
int NetClient_GetCameraParam(int _iLogonID, void * _lpBuf, int _iBufSize);
int NetClient_SetColorParam(int _iLogonID,int _iChannelNum, int _iColorToGradEnable, int _iDayRange, int _iNightRange);
int NetClient_GetColorParam(int _iLogonID,int _iChannelNum, int* _iColorToGradEnable,  int* _iDayRange, int* _iNightRange);
void* NetClient_InnerMallocBlock(int _iNeedSize);
int NetClient_InnerFreeBlock(void * _pBlock);
int NetClient_InnerReferBlock(void * _pBlock);
int NetClient_InnerReleaseBlock(void* _pBlock);
int NetClient_SetJPEGQuality(int _iLogonID, int _iJpegQuality);
int NetClient_GetJPEGQuality(int _iLogonID, int* _iJpegQuality);
int NetClient_GetConnectInfo(int _iLogonID, void* _lpBuf, int _iSize);
int NetClient_SetPlatformApp(int _iLogonID, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_GetPlatformApp(int _iLogonID, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_SetManagerServersInfo(int _iLogonID, char* _cRegSvrIP, unsigned short _wdRegPort,
            char* _cHeartSvrIP, unsigned short _wdHeartPort, char* _cAlarmSvrIP, unsigned short _wdAlarmPort);
int NetClient_GetManagerServersInfo(int _iLogonID, char* _cRegSvrIP, unsigned short* _wdRegPort,
            char* _cHeartSvrIP, unsigned short* _wdHeartPort, char* _cAlarmSvrIP, unsigned short* _wdAlarmPort);
int NetClient_SetDeviceID(int _iLogonID, char* _cDeviceID, char* _cDeviceName, unsigned short _iVspPort, char* _cAccessPass, unsigned short _iVapPort);
int NetClient_GetDeviceID(int _iLogonID, char* _cDeviceID, char* _cDeviceName, unsigned short* _iVspPort, char* _cAccessPass, unsigned short* _iVapPort);
int NetClient_SetATMConfig(int _iLogonID,int _iCmd, void* _lpBuf);
int NetClient_GetATMConfig(int _iLogonID,int _iCmd, void* _lpBuf);
int NetClient_ATMQueryFile(int _iLogonID, int _iCmd, void* _lpBuf);
int NetClient_ATMGetQueryFile(int _iLogonID, int _iFileIndex, ATM_FILE_DATA* _pFileData);
int NetClient_SetAudioSample(int _iLogonID, int _iChannel,int _iCmd, void* _lpBuf);
int NetClient_GetAudioSample(int _iLogonID, int _iChannel,int _iCmd, void* _lpBuf);
int NetClient_SetSystemTypeEx( int _iLogonID, int _iCmd, void* _pvCmdBuf);
int NetClient_GetSystemTypeEx( int _iLogonID, int _iCmd, void* _pvCmdBuf);
int NetClient_SetHXListenPortInfo(int _iLogonID,int _iVideoPort,int _iTalkPort,int _iMsgPort);
int NetClient_GetHXListenPortInfo(int _iLogonID,int* _iVideoPort,int* _iTalkPort,int* _iMsgPort);
int NetClient_SetVideoModeMethod(int _iLogonID, int _iChannel, VIDEO_METHOD  _iMethod);
int NetClient_GetVideoModeMethod(int _iLogonID, int _iChannel, VIDEO_METHOD * _piMethod);
int NetClient_GetMonitorNum();
int NetClient_GetMonitorInfo(unsigned int _uiIndex,MONITOR_INFO* _MonitorInfo);
int NetClient_ChangeMonitor(int _iLogonID,int _iChannelNum,unsigned int _uiIndex, int _iStreamNO);
int NetClient_EZoomAdd(unsigned int _uiConnID, int _hWnd, RECT _rctDisplay, unsigned int _uiMonitorIndex);
int NetClient_EZoomSet(unsigned int _uiConnID, int _iEZoomID, RECT _rctVideo);
int NetClient_EZoomReset(unsigned int _uiConnID, int _iEZoomID);
int NetClient_EZoomRemove(unsigned int _uiConnID, int _iEZoomID);
int NetClient_DCardStartPlay(unsigned int _ulConID, int _iCardChannel, int _iPos);
int NetClient_DCardStopPlay(unsigned int _ulConID, int _iFlag);
int NetClient_DCardRelease();
int NetClient_DCardReInit(int _iCardChannel);
int NetClient_DCardGetState(int _iCardChannel, int* _iState);
int NetClient_DCardStartPlayEx(int* _iId, DecoderParam* _dParam);
int NetClient_DCardPutDataEx(int _iId, char* _cBuf, int _iLen);
int NetClient_DCardStopPlayEx(int _iId, int _iFlag);
int NetClient_DCardStartPlayAudio(unsigned int _ulConID);
int NetClient_SetEncryptSN( int _iLogonID,int _iType,char* _cSN);
int NetClient_GetSNReg( int _iLogonID,int* _piLockRet);
int NetClient_GetComFormat_V1(int _iLogonID, int _iComPort,char* _cDeviceType,char* _cCommFormat,int* _iWorkMode);
int NetClient_SetComFormat_V2(int _iLogonID, COMFORMAT* _pComFormat);
int NetClient_GetComFormat_V2(int _iLogonID, COMFORMAT* _pComFormat);
int NetClient_GetServerVersion_V1(int _iLogonID, SERVER_VERSION* _pstrctServerVer);
int NetClient_InputTalkingdataEx(int _iLogonID, unsigned char* _ucData, unsigned int _iLen);
int NetClient_SetVerticalSync(unsigned int _ulConID,int _iFlag);
int NetClient_GetVerticalSync(unsigned int _ulConID,int* _piFlag);
int NetClient_SetLocalAudioVolumeEx(unsigned int _ulConID, int _iVolume);
int NetClient_GetLocalAudioVolumeEx(unsigned int _ulConID, int* _iVolume);
int NetClient_ClearPolyLocalVideo(unsigned int _uiConnID, int _iPolygonIndex);
int NetClient_SetOSDTypeFontSize(int _iLogonID,int _iChannelNum,int _iOSDType, int _iSize);
int NetClient_GetOSDTypeFontSize(int _iLogonID,int _iChannelNum,int _iOSDType, int* _iSize);
int NetClient_SetImgDisposal( int _iLogonID,void * _lpBuf, int _iBufSize);
int NetClient_GetImgDisposal( int _iLogonID,void * _lpBuf, int _iBufSize);
int NetClient_SetMuted(unsigned int _uiConID, int _iMuted);
int NetClient_SetPWMValue(int _iLogonID, int _iChannelNo, int _iValue);
int NetClient_GetPWMValue(int _iLogonID, int _iChannelNo, int* _piValue);
int NetClient_SetSystemType( int _iLogonID,int _iType);
int NetClient_GetSystemType( int _iLogonID,int* _piType);
int NetClient_SetITSSwitchTime(int _iLogonID, int _iSwitchTime, int _iDelayTime);
int NetClient_GetITSSwitchTime(int _iLogonID, int* _iSwitchTime, int* _iDelayTime);
int NetClient_SetITSRecoParam(int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_GetITSRecoParam(int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_SetITSDayNight(int _iLogonID, int _iTimeSegment);
int NetClient_GetITSDayNight(int _iLogonID, int* _iTimeSegment);
int NetClient_SetITSCamLocation(int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_GetITSCamLocation(int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_SetITSWorkMode(int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_GetITSWorkMode(int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_SetWaterMarkEnable( int _iLogonID,int _iChannelID,int _iEnable);
int NetClient_GetWaterMarkEnable( int _iLogonID,int _iChannelID,int* _piEnable);
int NetClient_SetITSLightInfo(int _iLogonID, void * _lpBuf, int _iBufSize);
int NetClient_GetITSLightInfo(int _iLogonID, void * _lpBuf, int _iBufSize);
int NetClient_SetHardWareParam( int _iLogonID, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_GetHardWareParam( int _iLogonID, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_SetDomeAdvParam( int _iLogonID, int _iChannelNO, int _iCmd, void* _pvCmdBuf, int _iCmdBufLen);
int NetClient_GetDomeAdvParam( int _iLogonID, int _iChannelNO, int _iCmd, void* _pvCmdBuf, int _iCmdBufLen);
int NetClient_SetDiskGroup( int _iLogonID,void* _lpBuf, int _iDiskGroupNum);
int NetClient_GetDiskGroup( int _iLogonID,void* _lpBuf, int _iDiskGroupNum);
int NetClient_SetDiskQuota( int _iLogonID, int _iChannel, void* _lpBuf, int _iBufSize);
int NetClient_GetDiskQuotaState ( int _iLogonID, int _iChannelNo, int _iCmd, void* _lpBuf, int _iBufSize );
int NetClient_ModifyUserAuthority( int _iLogonID, char* _pcUserName, void* _lpBuf, int _iBufSize );
int NetClient_GetUserAuthority( int _iLogonID, char* _pcUserName, void* _lpBuf, int _iBufSize );
int NetClient_GetGroupAuthority( int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_NetFileGetQueryfileEx(int _iLogonID,int _iFileIndex, PNVS_FILE_DATA_EX _pFileInfo);
int NetClient_NetFileLockFile( int _iLogonID, char* _cFileName, int _iLock);
int NetClient_GetOsdTextEx(int _iLogonID,int _iChannel,void* _lpBuf, int _iBufSize);
int NetClient_SetHolidayPlan(int _iLogonID,int _iCmd,void* _lpBuf, int _iBufSize);
int NetClient_GetHolidayPlan(int _iLogonID,int _iCmd,void* _lpBuf, int _iBufSize);
int NetClient_SetCommonEnable( int _iLogonID, int _iEnableID, int _iChannel, int _iEnableValue );
int NetClient_GetCommonEnable( int _iLogonID, int _iEnableID, int _iChannel, int* _iEnableValue );
int NetClient_NetFileDownload(unsigned int* _ulConID, int _iLogonID, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_Upgrade_V4(int _iLogonID, char* _cFileName, int _iUpgradeType, UPGRADE_NOTIFY_V4 _UpgradeNotify);
int NetClient_GetAudioCoderList( int _iLogonID, int _iChannel, int _iStreamNo, int* _piList, int* _piLstCount );
int NetClient_InnerAutoTest(int _iLogonID, int _iCmd, void* _pvTestBuf, int _iBufSize);
int NetClient_SetJEPGSize(int _iLogonID, int _iChannelNo, int _iWidth, int _iHeight);
int NetClient_GetJEPGSize(int _iLogonID, int _iChannelNo, int* _iWidth, int * _iHeight);
int NetClient_QueryDevStatus(int _iLogonID, int _iType);
int NetClient_GetDevStatus(int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_GetHDTemplateIndex(int _iLogonID, int _iChannelNo /*= 0*/, int* _iTemplateIndex);
int NetClient_SetStreamInsertData(int _iLogonID, int _iChannelNo, int _iFlag, int _iType, void* _pDataBuf, int _iDataLen);
int NetClient_GetStreamInsertData(int _iLogonID, int _iChannelNo, int _iFlag, int _iType, void* _pDataBuf, int _iDataLen);
int NetClient_GetOtherID(int _iLogonID, void* _pcBuff, int _iBufLen);
int NetClient_SetDomePTZ(int _iLogonID, int _iChannelNo, void* _lpBuf, int _iBufSize);
int NetClient_GetDomePTZ(int _iLogonID, int _iChannelNo, void* _lpBuf, int _iBufSize);
int NetClient_GetUserDataInfo(unsigned int _ulConID, int _iFlag, void*  _pBuffer, int _iSize);
int NetClient_GetBroadcastMessage( int _iLogonID,void* _lpBuf, int _iBufSize);
int NetClient_GetModuleCapability( int _iLogonID,int _iModule,unsigned int* _uCaps);
int NetClient_KeyboardCtrl(char* _pcIP, int _iAction,int _iValue);
int NetClient_NetFileSetSchedule(int _iLogonID, int _iChannel,int _iCmd,void* _lpBuf, int _iBufSize);
int NetClient_NetFileGetSchedule(int _iLogonID, int _iChannel, int _iCmd, void* _lpBuf, int _iBufSize);
int NetClient_SetDevConfig(int _iLogonID, int _iCommand, int _iChannel, void* _lpInBuffer, int _iInBufferSize);
int NetClient_GetDevConfig(int _iLogonID, int _iCommand, int _iChannel, void* _lpOutBuffer, int _iOutBufferSize, int* _lpBytesReturned);
int NetClient_SendCommand(int _iLogonID,  int _iCommand,  int _iChannel,  void* _pBuffer,  int _iBufferSize);
int NetClient_RecvCommand(int _iLogonID,  int _iCommand,  int _iChannel,  void* _pBuffer,  int _iBufferSize);
int NetClient_SetDevDiskConfig (int _iLogonID, int _iCommand, int _iChannel, void* _lpInBuffer, int _iInBufferSize);
int NetClient_GetDevDiskConfig (int _iLogonID, int _iCommand, int _iChannel, void* _lpOutBuffer, int _iOutBufferSize, int* _lpBytesReturned);
int NetClient_Logon_V4(int _iLogonType, void* _pvPara, int _iInBufferSize);
int NetClient_PlayBackControl(unsigned long _ulConID, int _iControlCode, void* _pcInBuffer, int _iInLen, void* _pcOutBuffer, int* _iOutLen);
int NetClient_PlayerControl(unsigned int _uiRecvID, int _iCmd, void* _pvCmdBuf, int _iBufLen, void* _pvUsrData);
int NetClient_StopPlayBack(unsigned long _ulConID);
int NetClient_PlayBack(unsigned int* _ulConID, int _iCmd, PlayerParam* _PlayerParam, void* _hWnd);
int NetClient_GetPseChInfo(int _iLogonID, void* _lpBuf, int _iBufSize);
int NetClient_SetPseChProperty(int _iLogonID, int _iPseCh, void* _lpBuf, int _iBufSize);
int NetClient_GetPseChProperty(int _iLogonID, int _iPseCh, void* _lpBuf, int _iBufSize);
int NetClient_ChannelTalkStart(int _iLogonID, int _iChannel, int _iUser);
int NetClient_ChannelTalkEnd(int _iLogonID, int _iChannel);
int NetClient_InputChannelTalkingdata(int _iLogonID, int _iChannel, unsigned char* _ucData, unsigned int _iLen);
int NetClient_GetChannelTalkingState(int _iLogonID, int _iChannel, int* _iTalkState);
int NetClient_CapturePicture(unsigned int _ulConID, int _iPicType, char* _pcFileName);
int NetClient_CapturePicData(unsigned int _ulConID, int _iPicType, char* _pcPicBuf, int* _piPicSize);
int NetClient_SetSDKWorkMode(int _iWorkMode);
int NetClient_Query_V4(int _iLogonID, int _iCmd, int _iChannel, void* _pvCmdBuf, int _iBufLen);
int NetClient_GetQueryResult_V4(int _iLogonID, int _iCmd, int _iChannel, int _iIndex, void* _pvCmdBuf, int _iBufLen);
int NetClient_RebootDeviceByType(int _iLogonID, int _iType, void* _pvCmdBuf, int _iBufLen);
int NetClient_StartDownload(int _iLogonID, int _iChannel, int _iDownloadMode, void* _lpInBuf, int _iInBufLen
									  , unsigned long* _pulDownloadFd);
int NetClient_StopDownload(unsigned long _ulDownloadFd);
int NetClient_GetDownloadPos(unsigned long _ulDownloadFd, int* _puiDownloadPos);
int NetClient_ProxySend (int _iProtocolType, bool _blSend);
int NetClient_SetDevUserDataNotify(unsigned int _uiRecvID, DEVUSERDATA_NOTIFY _cbkDevUserData, void* _pvUdata);
int NetClient_SetDsmConfig(int _iCommand, void* _pvBuf, int _iBufSize);
int NetClient_GetDsmRegstierInfo(int _iCommand, void* _pvBuf, int _iBufSize);
int NetClient_GetRecvInfoById(int _iRecvId, void* _pvBuf, int _iBufSize);
int NetClient_GetParamFromDevice(int _iLogonID, int _iChannel, void* _lpBuf, int _iBufSize);
int NetClient_GetPlayerIndex(unsigned int _uiConID);
int NetClient_GetRealPlayerIndex(unsigned int* _ulConID);
int NetClient_StartRecvNetPicStream(int _iLogonID, NetPicPara* _ptPara, int _iBufLen, unsigned int* _puiRecvID);
int NetClient_StopRecvNetPicStream(unsigned int _uiRecvID);
int NetClient_SetProxyNotifyFunction(MAIN_NOTIFY_V4     _ProxyMainNotify,
											 PROXY_NOTIFY       _ProxyNotify);
int NetClient_SetExternDevLogonInfo(unsigned int _uiAllowDevType);
int NetClient_SetUnipueAlertConfig(int _iLogonId, int _iCmdId, int _iChannel, void* _lpCmdBuf, int _iCmdBufLen);
int NetClient_GetUnipueAlertConfig(int _iLogonId, int _iCmdId, int _iChannel, void* _lpCmdBuf, int _iCmdBufLen);
int NetClient_FaceConfig(int _iLogonId, int _iCmdId, int _iChanNo, void* _lpIn, int _iInLen, void* _lpOut, int _iOutLen);
int NetClient_Query_V5(int _iLogonId, int _iCmdId, int _iChanNo, void* _lpIn, int _iInLen, void* _lpOut, int _iOutLen);
int NetClient_SetAlarmNotify_V5(ALARM_NOTIFY_V5 _pAlarm);
int NetClient_Upgrade_V5(int _iLogonId, int _iType, void* _lpBuf, int _iBufSize);
int NetClient_CmdConfig(int _iLogonId, int _iCmdId, int _iChanNo, void* _lpIn, int _iInLen, void* _lpOut, int _iOutLen);
int NetClient_GetLastError();
int NetClient_GetConncetInfo(unsigned int _ulConID, int _iCmdId, void* _pvCmdBuf, int _iCmdBufLen);
int NetClient_SyncLogon(int _iLogonType, void* _pvPara, int _iParaSize);
int NetClient_SyncRealPlay(unsigned int* _puiRecvID, NetClientPara* _ptPara, int _iParaSize);
int NetClient_StopRealPlay(unsigned int _uiRecvID, int _iParam);
int NetClient_SyncQuery(int _iLogonID, int _iChanNo, int _iCmd, void* _pvInPara, int _iInLen, void* _pvOutPara, int _iOutTotalLen, int _iSingleLen);
int NetClient_SyncSetDevCfg(int _iLogonID, int _iChanNo, int _iCmd, void* _pvInPara, int _iInLen, void* _pvOutRet, int _iOutLen);
int NetClient_CapturePicByDevice(int _iLogonID, int _iChanNo, int _iQvalue, char* _pcPicFilePath, SnapPicData* _ptSnapPicData, int _iInSize);
int NetClient_SetSDKInitConfig(int _iCmd, void* _lpInBuffer, int _iInBufferSize);
int NetClient_SetAVMode(int _iRecvID, int _iCmd, void* _pvBuf, int _iBufSize);
void* NetClient_CreateQtWidget(void* _pvParaBuf, int _iBufSize);
int NetClient_ReleaseQtWidget(void* _pvQWidget);
int NetClient_GetDevConfig_V5(int _iLogonID, int _iCmd, void* _pvInParaBuf, int _iInBufLen, void* _pvOutParaBuf, int _iOutBufLen);
int NetClient_SycVoiceTalkStart(unsigned int* _puiTalkID, NetVoiceTalkPara* _pvPara, int _iSize);
int NetClient_SycVoiceTalkStop(unsigned int _uiTalkID, void* _pvPara, int _iSize);
int NetClient_SycVoiceTalkInputData(NetVoiceTalkInput* _pvPara, int _iSize);
int NetClient_HttpXmlConfig(int _iLogonID, XmlCfgInPara* _ptXmlInPara, int _iInSize, XmlCfgOutPara* _ptXmlOutPara, int _iOutSize);
int NetClient_XmlSetDevConfig(int _iLogonID, int _iCmd, void* _pvInPara, int _iInSize, void* _pvOutRet, int _iOutSize);
int NetClient_XmlGetDevConfig(int _iLogonID, int _iCmd, void* _pvInPara, int _iInSize, void* _pvOutRet, int _iOutSize);


#endif

