-- 主键 & 自增信息
SELECT 'PK' AS kind, t.TABLE_NAME, c.COLUMN_NAME, c.EXTRA
FROM INFORMATION_SCHEMA.COLUMNS c
JOIN INFORMATION_SCHEMA.TABLES t ON c.TABLE_SCHEMA=t.TABLE_SCHEMA AND c.TABLE_NAME=t.TABLE_NAME
WHERE c.TABLE_SCHEMA='ch_ibms' AND c.COLUMN_KEY='PRI'
  AND (t.TABLE_NAME LIKE 'ibms_%' OR t.TABLE_NAME LIKE 'iot_%' OR t.TABLE_NAME LIKE 'security_%'
       OR t.TABLE_NAME LIKE 'access_parking_%'
       OR t.TABLE_NAME IN ('building','area','campus','floor'))
  AND t.TABLE_NAME NOT LIKE 'bak_%'
ORDER BY t.TABLE_NAME;
