;Get(0:所有通道,1:指定通道),Set(0:所有通道,1:指定通道),中文名,英文名
[module0]
name_zh=通用使能
name_en=Common Enable
id_start=0x12000
0x12001=0,0,GPS 校时,GPS Check Time
0x12002=0,0,低压报警阈值,Vehicle Alarm Threshold
0x12003=0,0,低压关机阈值,Vehicle Shut Dowm Threshold
0x12010=1,1,ANR使能,ANR Enable
0x12011=0,0,工作机热备,Work Device Back Up
0x12012=0,0,禁用通道数,Forbid Channel Number
0x12013=1,1,事件模板,Event Template
0x12014=0,0,Telnet,Telnet
0x12015=0,0,弹盘封盘状态,Disk Status
0x12016=0,0,过车检测,Car Check
0x1203F=1,1,是否开启红外视频,Open Infrared video
0x12040=0,0,设置主网卡号,Set Primary NIC Number
0x12041=0,0,人脸PAD设备数据清除,Face pad data clear
0x12042=0,0,人脸PAD存储策略,Face pad storage strategy
0x12043=0,0,设置远程开门（门禁设备使用）,Device Remote Open Door
0x12044=0,0,人脸PAD语音提示使能,Face pad voice tips
0x12045=0,0,门禁设备模式,Guarded device mode
0x12046=0,0,人脸PAD公共密码是否启用,Face pad public password
0x12047=0,0,人脸PAD用户模式切换请求,Face pad user mode switch
0x12048=0,0,人脸PAD检测模式设置请求,Face pad check mode set

[module1]
name_zh=网络连接
name_en=Net Connection
id_start=0xD000
0xD001=0,0,MTU设置,MTU Set
0xD002=0,0,公网连接状态,Public Net Severice Status

[module2]
name_zh=智能分析
name_en=VCA
id_start=0xE000
0xE000=0,0,NVR 本地智能分析,NVR Local Smart Analysis
0xE006=0,0,智能资源切换,Intelligent resource switching
0xE007=0,0,是否发送人脸特征,Send Face Feature
0xE008=0,0,IPC活体检测开关,IPC Live Detection
0xE00C=0,0,流速场实时数据上传开关,Real time data upload switch of velocity field 
0xE00E=0,1,流速数据缓存个数,Number of velocity data buffers 

[module3]
name_zh=网络服务
name_en=Net Service
id_start=0x7000
0x7000=0,0,SNMP,SNMP
0x7001=1,1,SMTP,SMTP
0x7002=0,0,RTSP,RTSP

[module4]
name_zh=存储
name_en=Storage
id_start=0x6000
0x6002=0,0,哈希校验,Hash Check
0x6003=1,1,音频文件生成,Storage Audio File
0x6004=0,0,音频文件刻录,Audio File Record
0x6005=0,0,音频文件备份,Audio File Backup
0x6006=0,0,实时刻录录像文件格式,Real-time Burning File Type

[module5]
name_zh=磁盘管理
name_en=Disk Management
id_start=0xA000
0xA000=0,0,盘组配合策略,Storage Disk Group
0xA001=0,0,配额模式,Disk Quota Mode
0xA002=0,0,RAID,RAID

[module6]
name_zh=智能交通
name_en=ITS
id_start=0x10000
0x10001=1,1,信号灯同步,Signal Synchronization
0x10002=0,0,交通业务,ITS Business
0x10003=0,0,违章停车抓拍类型,Illegal Park Capture Type
0x10008=0,0,夜间监控使能开关
0x10009=0,0,交通违法录像使能开关
0x1000A=0,0,上传交通违法录像（交通平台）开关
0x1000B=0,0,开启车牌增强,Turn on license plate enhancement
0x1000C=0,0,开启车牌二值图,Turn on license plate binary map

[module7]
name_zh=系统管理
name_en=System Setting
id_start=0xB000
0xB000=0,0,风扇远程控制,Fan Remote Control
0xB001=0,0,风扇温控,Fan Thermostat
0xB002=0,0,白光灯,White Light

[module8]
name_zh=音视频
name_en=Audio & Video
id_start=0x1000
0x1001=1,1,电子防抖,Electronic Image Stabilization
0x1002=1,1,SVC,SVC
0x1003=0,0,视频输出,Video Output
0x1004=1,1,音频去噪,Audio Denoise
0x1005=0,0,ROI,ROI
0x1006=1,1,视频翻转,Video Reverse
0x100B=0,0,鱼眼摄像机-安装方式,Fish-Eye Camera-Install Way
0x100C=0,0,鱼眼摄像机-预留模式,Fish-Eye Camera-Preview Mode


[module9]
name_zh=报警
name_en=Alarm
id_start=0x5000
0x5000=1,1,报警-MD,Alarm-MD
0x5001=1,1,报警-OD,Alarm-OD

[module10]
name_zh=字符叠加
name_en=OSD
id_start=0x2000
0x2001=1,1,点阵字库,Lattice
0x2002=1,1,矢量字库,Vector

[module11]
name_zh=外设管理
name_en=Peripheral Management
id_start=0x14000
0x14000=0,0,激光,Laser light
