#ifndef _CONFIG_WINDOW_H
#define _CONFIG_WINDOW_H

#include "afxcmn.h"
#include "../BasePage.h"
#include "VideoPage.h"

// CLS_ConfigWindow dialog

enum CONFIG_PAGE_INDEX
{
	CONFIG_MIN = 0,
	CONFIG_VIDEO_PARAM = CONFIG_MIN,
	CONFIG_VIDEO_PARAM_SCHEDULE,
	CONFIG_AUDIO_PARAM,
	CONFIG_VIDEO_ENCRYPT,
	CONFIG_VIDEO_ENCODE_SLICE,
	CONFIG_ALARM,
	CONFIG_LANGUAGE,
	CONFIG_OSD,
	CONFIG_OSD_BACK_GROUND,
	CONFIG_IP,
	CONFIG_DZ,
	CONFIG_SO,	
	CONFIG_USER,
	CONFIG_AUTHORITY_LOCAL,
	CONFIG_AUTHORITY_REMOTE,
	CONFIG_AUTHORITY_CHANNEL,
	CONFIG_SIP,
	CONFIG_REPORT_SET,
	CONFIG_CMOS,
	CONFIG_DDNS,
	CONFIG_UDP,
	CONFIG_NTP,
	CONFIG_OPTION_PU,
	CONFIG_ITS_ROADWAY_COMMON1,
	CONFIG_ITS_PICTURE_COMMON1,
	CONFIG_ITS_OSD,
	CONFIG_ITS_OSD_EX,
	CONFIG_ITS_ALARM_LINK,
	CONFIG_ITS_OTHER,
	CONFIG_LAN_IPV4,
	CONFIG_LAN_IPV6,
	CONFIG_LAN_WOKEMODE,
	CONFIG_LAN_HTTP,
	CONFIG_LAN_PORT,
	CONFIG_LAN_UPNP,
	CONFIG_FTP,
	CONFIG_LAN_QOS,
	CONFIG_LAN_RTMP,
	CONFIG_BURN,
	CONFIG_BURN_H323,
	CONFIG_BURN_H8,
	CONFIG_8D1,
    CONFIG_STORAGE,
	CONFIG_HARDDISK_INFO,
	CONFIG_STORAGE_DISKINFO,
	CONFIG_HOLIDAY_PLAN,
	CONFIG_STORAGE_STRATEGY,
	CONFIG_STORAGE_SMART,
	CONFIG_STORAGE_DISKMANAGE,
	CONFIG_STORAGE_ANR,
	CONFIG_STORAGE_HOTBACKUP,
	CONFIG_HD,
	CONFIG_ADV,
	CONFIG_NETTEST,
	CONFIG_DNVR_ALMSCH,
	CONFIG_DNVR_ALMLINK,
	CONFIG_DNVR_ALMLINKIPC,
	CONFIG_DEMO_CRUSIE,
	CONFIG_VCA_SMART_SEARCH,
	CONFIG_VCA_SMART_TRACK,
	CONFIG_DNVR_DIGIT,
	CONFIG_DNVR_VIDEOCOMBINE,
	CONFIG_DNVR_BAWSLICENCEPLATE,
	CONFIG_DNVR_EXCEPTION,
	CONFIG_DNVR_CREATEFREEV,//CREATEFREEVO add csl
	CONFIG_DNVR_TEXTPLAN,
	CONFIG_DNVR_CHANNEL_INFO,
	CONFIG_DNVR_XVR,
	CONFIG_XNVR_UPDATED,
	CONFIG_3G_NORMAL,
	CONFIG_3G_DVR,
	CONFIG_3G_ADV,
	CONFIG_4G_NORMAL,
	CONFIG_VEHICLE,
	CONFIG_LOG_NVS,
	CONFIG_LOG_DVR,
	CONFIG_PTZ,
	CONFIG_WIFI,
	CONFIG_ATM,
	CONFIG_VCA_RESOURCE,
	CONFIG_VCA_TARGET,
	CONFIG_VCA_ADVANCE,
	CONFIG_VCA_EVENTS_ADV,
	CONFIG_VCA_EVENTS,
	CONFIG_VCA_ALARM,

	CONFIG_ALARM_HUM_TEM,
	CONFIG_VCA_QUERY_FILES,
	CONFIG_VCA_TARGET_PICTURE_MNG,		// target image parameters
	CONFIG_VCA_GPS_LOCATION,			//GPS location information
	CONFIG_VCA_FLUXSTATISTIC,
	CONFIG_VCA_MASK_AREA,
	CONFIG_VCA_DECTECT_AREA,			//Detection area
	CONFIG_VCA_SCAN_AREA,
	CONFIG_VCA_3DMASKAREA,
    CONFIG_VCA_CALIBRATEMODE,            //Set the calibration method
    CONFIG_VCA_SCENE_HDSCHEDULE_PARA, //Scene HD template parameters
    CONFIG_VCA_SCENE_FOCUSAREA_PARA,     //Scene key area parameters
	CONFIG_VCA_CPC_AREA,                 // area population statistics

	CONFIG_COM,
	CONFIG_PERIPHERAL,
	CONFIG_IOPORT,
	CONFIG_ADVANCE_VERSION,
	CONFIG_ADVANCE_SYSTEM,
	CONFIG_ADVANCE_PROT_DETECT,		//Protocol detection
	CONFIG_ADVANCE_COMMONENABLE,	//General enable TDY
	CONFIG_ADVANCE_FUNCASSEMBLE,	//ability set
	CONFIG_ADVANCE_FUNC_CTG,		//color to black
	CONFIG_ADVANCE_FUNC_VTC,		//Video transcoding
	CONFIG_ADVANCE_FUNC_DDNS,		//DDNS
	CONFIG_ADVANCE_FUNC_PEOPLENUM,	//People Counting
	CONFIG_ADVANCE_FUNC_POTICS_LAW,	//political and legal business
	CONFIG_ADVANCE_FUNC_DECODER,	//decoder business
	CONFIG_ADVANCE_FUNC_ROI,		//ROI
	CONFIG_ADVANCE_FUNC_DOME,		// ball machine parameters
	CONFIG_ADVANCE_FUNC_SMARTA,		//Insight
	CONFIG_ADVANCE_FUNC_NETWORK,	//network
	CONFIG_ADVANCE_VCATOPS,
	CONFIG_ADVANCE_FUNC_SUPPORT,      //Whether a capability is supported
	CONFIG_ADVANCE_UPGRADE,
	CONFIG_ADVANCE_CHANNEL,
	CONFIG_ADVANCE_LOCAL,
	CONFIG_VCA_ALARM_INFO,
	CONFIG_VCA_ALARM_SCHEDULE,
	CONFIG_VCA_ALARM_LINK,
	CONFIG_COOPER_DOME,
	CONFIG_VIDEO_INTERESTED,
	CONFIG_APPEND_OSD,
	CONFIG_DOME_STATE,
	CONFIG_DOME_SCHEDULE,
	CONFIG_DOME_MENU,
	CONFIG_WHITE_LIGHT,
	CONFIG_HTTPPICTURE,
	CONFIG_WIRELESS_SILENT,
	CONFIG_FTP_UPLOAD,
	CONFIG_IPADV,
	CONFIG_DONGHUAN_SET,
	CONFIG_DONGHUAN_LINKSET,
	CONFIG_DONGHUAN_COMFORT,
	CONFIG_DONGHUAN_SCHEDULE,
	CONFIG_DONGHUAN_OSDSET,
	CONFIG_DONGHUAN_DATA,
	CONFIG_DOME_HD1,
	CONFIG_DOME_HD2,
	CONFIG_DOME_HD3,
	CONFIG_HD_SCHEDULE,
	CONFIG_DOME_BASIC1,
	CONFIG_DOME_BASIC2,
	CONFIG_DOME_RUN1,
	CONFIG_DOME_RUN2,

	CONFIG_ITS_PICTURE_COMMON2,
	CONFIG_ITS_PICTURE_COMMON3,
	CONFIG_ITS_PICTURE_OTHER,
	CONFIG_ITS_SIGNAL_CHECK,
	CONFIG_ITS_SIGNAL_OTHER,
	CONFIG_ITS_ROADWAY_COMMON2,
	CONFIG_ITS_ROADWAY_COMMON3,
	CONFIG_ITS_ROADWAY_COMMON4,
	CONFIG_ITS_ROADWAY_ADVANCED1,
	CONFIG_ITS_ROADWAY_ADVANCED2,
	CONFIG_ITS_RECOPARAM,
	CONFIG_ITS_RECOPARAM2,
	CONFIG_ITS_SYSTEMPARAM1,
	CONFIG_ITS_SYSTEMPARAM2,
	CONFIG_ITS_SYSTEMPARAM3,

	CONFIG_ITS_COMPO_PIC,
	CONFIG_ITS_TRAFFIC_STATIS,
	CONFIG_ITS_PARKCARNUM,
	CONFIG_ITS_ILLEGAl_TYPE,
	CONFIG_ITS_STATE_QUERY,
	CONFIG_ITS_FOCUS_AID,
	CONFIG_ITS_ROADWAY_ADVANCED3,
	CONFIG_ITS_ROADWAY_CAPTURECFG,
	CONFIG_ITS_EXTENDED_CONFIG1,
	CONFIG_ITS_EXTENDED_CONFIG2,
	CONFIG_AUTO_TEST,
	CONFIG_AUTO_TEST_MULT,
	CONFIG_THERMOGRAPHY,
	CONFIG_ITS_IO,
	CONFIG_ITS_PLATFORM_CFG,
	CONFIG_ITS_DEV_MANAGE,
	CONFIG_ITS_LANE_MANAGE,
	CONFIG_ITS_BAYONET_DATA,
	CONFIG_FEC,
	CONFIG_FEC_HEAT_MAP,
	CONFIG_STORAGE_SET,
	CONFIG_UNIQUE_ALERT,
	CONFIG_UNIQUE_ALERT_ENABLE_STATUS,
	CONFIG_UNIQUE_ALERT_PLAN,
	CONFIG_UNIQUE_ALERT_CUSTOM_EVENT,
	CONFIG_UNIQUE_ALERT_CUSTOM_EVENT_PERIMETER,
	CONFIG_UNIQUE_ALERT_CUSTOM_EVENT_TRIPWIRE,
	CONFIG_UNIQUE_ALERT_ALARM_LINK,
	CONFIG_UNIQUE_ALERT_FUNC_ASSEMBLE,
	CONFIG_UNIQUE_ALERT_ALARM_MESSAGE,
	CONFIG_UNIQUE_ALERT_TARGET,
	COMFIG_IRRIGATION_NOTIFY,
	COMFIG_IRRIGATION_PARAM,
	COMFIG_GENERAL_CONFIG,
	CONFIG_GAUGE_CALIB,
	CONFIG_DEV_DORMANCY,
	CONFIG_TRIBLE_VCA,
	CONFIG_TRIBLE_VCA_CONF,
	CONFIG_SNMP,
	CONFIG_CSPM,
	CONFIG_SHDB,
	CONFIG_INTERNATION_PRO,
	CONFIG_FIXED_DISK_STORAGE,
	CONFIG_TARGET_DETECT,
	CONFIG_HTTP_XML_CFG,
	CONFIG_ITS_RADAR_CFG,
	CONFIG_ITS_RADAR_LED_CFG,
	CONFIG_ITS_CALIBRATE,
	CONFIG_TRAFFIC_VIOLATION,
	CONFIG_FDD_FUNCTION,
	CONFIG_WATER_INFO,
	CONFIG_WATERFLOW_EDIT,
    CONFIG_GAT,
    CONFIG_WIEGAND,
	CONFIG_PLATFORMACCESS,
	CONFIG_GB28181SET,
	CONFIG_AIRLINEINFO,
	CONFIG_CGIBUSINESSMODULE,
	CONFIG_4KTRIAL,
	CONFIG_PROOFADJUST,					//Proof adjustment
	CONFIG_PERVIEW_CHNSWITCH,			//Preview channel quick switch settings
	CONFIG_BESTIRCHN_CFG,				//Excitation channel configuration
	CONFIG_CALIBRATION_REFERENCE,		//Set/get the calibration reference frame
	CONFIG_RTPSERVERINFO,				//RTP multicast server IP
	CONFIG_CERTIFICATE_AUTHFILE,		//Get the certificate and create the authentication file
	CONFIG_CHANNEL_ALARMINFO,
	CONFIG_COURT_COMMONENABLE,
	CONFIG_COURTAVP_H323_LOCALPARAM,
	CONFIG_COURTAVP_H323_CALLSTATE,
	CONFIG_COURTAVP_H323_CALLDEVINFO,
	CONFIG_COURTAVP_H323_SUBSTREAM,
	CONFIG_SEND_COMMONDATA,        //send generic data
	CONFIG_SCHEDULES_JUDGE,
	CONFIG_SMART_PIC_QUERY,
	CONFIG_VCA_GUAGEINFO,				// water gauge information for water level detection
	CONFIG_VCA_WATERSPEED,				//Rule parameter (flow rate)
	CONFIG_VCA_WSTABLEUSEMODE,			// flow meter usage mode
	CONFIG_VERTICAL_LINE_QUERY,			//Query the result data of intelligent analysis of vertical line information of water conservancy channel section
	CONFIG_THREEDIMTRANS,
	CONFIG_ONVIF_VCAALARM,				//Send third-party intelligent analysis alarm message
	CONFIG_ELEVATOR_BUSINESSMODULE,
	CONFIG_ELEVATOR_MONITOR,
	CONFIG_ELEVATOR_STATE,
	CONFIG_ZFCHNINFO,
	CONFIG_VCA_RADARLINKSCENE,			//Set/get radar linkage scene parameters
	CONFIG_VCA_REFBOUNDARYINFO,			//Set/get the front-end device world coordinate system check boundary range
	CONFIG_CGI_FALLINGOBJECT,
	CONFIG_ELEVATOR_ALLSTATE,
	CONFIG_ALARM_COUNT,
	CONFIG_MIX_AUDIO_CONFIG,
	CONFIG_POLICECLOTH,
	CONFIG_PRISONERCLOTH,
	CONFIG_QUEUESTAND,
	CONFIG_VCA_IRRIDATAUPLOADPARAM,
	CONFIG_VCA_ELECTRONIC_FENCE,		//Electronic fence configuration
	CONFIG_VCA_IRRRECEIVERMSG,
	CONFIG_LICENSE_PLATE_MANAGEMENT,
	CONFIG_PLATELIB,
	CONFIG_STRATEGY_CONDITION,
	CONFIG_STRATEGY_INPUT,
    CONFIG_UNIQUE_ALERT_CUSTOM_EVENT_CLIMBWALL,
	CONFIG_MAX,
};

class CLS_ConfigWindow : public CLS_BaseWindow
{
	DECLARE_DYNAMIC(CLS_ConfigWindow)

public:
	CLS_ConfigWindow(CWnd* pParent = NULL);   // standard constructor
	virtual ~CLS_ConfigWindow();

// Dialog Data
	enum { IDD = IDD_DLG_CONFIG };

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

	DECLARE_MESSAGE_MAP()

public:
	virtual BOOL OnInitDialog();
	virtual void OnChannelChanged(int _iLogonID,int _iChannelNo,int _iStreamNo);
	virtual void OnLanguageChanged(int _iLanguage);
	virtual void OnMainNotify(int _ulLogonID,int _iWparam, void* _iLParam, void* _iUser);
	virtual void OnParamChangeNotify(int _iLogonID, int _iChannelNo, int _iParaType,void* _pPara,int _iUser);
	virtual void OnAlarmNotify(int _iLogonID, int _iChannelNo, int _iAlarmState,int _iAlarmType,int _iUserData);
	virtual void OnAlarmNotify_V5(int _iLogonID, int _iAlarmType, void* _pInfo, int _iSize, void* _pUser);
	afx_msg void OnShowWindow(BOOL bShow, UINT nStatus);
	afx_msg void OnDestroy();
	afx_msg void OnNMDblclkTreeConfig(NMHDR *pNMHDR, LRESULT *pResult);
	afx_msg void OnTvnSelchangedTreeConfig(NMHDR *pNMHDR, LRESULT *pResult);
	
private:
	int ShowBasePage( int _iIndex );
	int LockPage(BOOL _bLocked);
	void UI_UpdateDialog();
	BOOL ShowVideo();
	BOOL CloseVideo();

private:
	CTreeCtrl m_tvConfig;
	CLS_BasePage* m_pPage[CONFIG_MAX];
	CLS_BasePage* m_pCurrent;
	CLS_VideoPage* m_pVideo;
	int m_iLogonID;
	int m_iChannelNo;
	int m_iStreamNo;
	BOOL m_bLocked;
	int m_iCurrentPage;
public:
	void ChangeCurrentPage();
	afx_msg void OnStnClickedStaticCenterBg();
};

#endif

