
// FaceDemo. Cpp: defines the class behavior of the application.
//

#include "stdafx.h"
#include "MfcFaceDemo.h"
#include "FaceDemoDlg.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

BEGIN_MESSAGE_MAP(CFaceDemoApp, CWinApp)
	ON_COMMAND(ID_HELP, &CWinApp::OnHelp)
END_MESSAGE_MAP()

CFaceDemoApp::CFaceDemoApp()
{
}

CFaceDemoApp theApp;

BOOL CFaceDemoApp::InitInstance()
{
	//If an application manifest running on Windows XP specifies that
	//Use ComCtl32.dll version 6 or later to enable visualization,
	//InitCommonControlsEx() is required. Otherwise, the window cannot be created.
	INITCOMMONCONTROLSEX InitCtrls;
	InitCtrls.dwSize = sizeof(InitCtrls);
	//Set it to include all the
	//Common control class.
	InitCtrls.dwICC = ICC_WIN95_CLASSES;
	InitCommonControlsEx(&InitCtrls);

	CWinApp::InitInstance();

	AfxEnableControlContainer();

	//Standard initialization
	//If you do not use these functions and want to reduce
	//The size of the final executable file, the following should be removed
	//Specific initialization routines not required
	//Change the registry key used to store settings
	//TODO: The string should be modified appropriately,
	//For example, change to company or organization name
	SetRegistryKey(_T("Local application generated by application wizard"));

	CFaceDemoDlg dlg;
	m_pMainWnd = &dlg;
	INT_PTR nResponse = dlg.DoModal();
	if (nResponse == IDOK)
	{
		//TODO: When to use this place for processing
		//OK to close the code of the dialog box
	}
	else if (nResponse == IDCANCEL)
	{
		//TODO: When to use this place for processing
		//Cancel to close the code of the dialog box
	}

	//Because the dialog box is closed, FALSE will be returned to exit the application,
	//Instead of starting the application's message pump.
	return FALSE;
}
