//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MfcFaceDemo.rc
//
#define IDD_DEMOFACE_DIALOG             102
#define IDR_HTML_LS_DLGFACEALARM        103
#define IDR_MAINFRAME                   128
#define IDD_DLG_CFG_FACE_FEATURE        129
#define IDD_DLG_CFG_FACE_ALARM          130
#define IDD_DLG_CFG_FACE_SCHEDULE       131
#define IDD_DLG_CFG_FACE_ADVANCE        132
#define IDD_DLG_CFG_FACE_LIB            133
#define IDD_DLG_CFG_FACE_STREAM         134
#define IDD_DLG_CFG_FACE_PIC            135
#define IDD_DLG_CFG_FACE_SEARCH         136
#define IDD_DLG_CFG_FACE_ALARM_LINK     137
#define IDD_DLG_CFG_FACE_PROCESS        138
#define IDD_DLG_CFG_FACE_SEARCH_SNAP    139
#define IDD_DLG_CFG_FACE_LIB_EDIT       140
#define IDD_DIALOG1                     141
#define IDD_DLG_CFG_FACE_PIC_EDIT       141
#define IDD_DLG_CFG_FACE_DETECTION      142
#define IDD_DLG_CFG_FACE_LIB_SYNC       143
#define IDC_TREE_CONFIG                 1000
#define IDC_EDT_PORT                    1001
#define IDC_EDT_USERNAME                1002
#define IDC_EDT_PASSWORD                1003
#define IDC_BTN_LOGON                   1005
#define IDC_BTN_LOGOFF                  1006
#define IDC_STC_PORT                    1007
#define IDC_STC_USERNAME                1008
#define IDC_STC_PASSWORD                1009
#define IDC_STC_CHANNO                  1010
#define IDC_CBO_CHANNO                  1011
#define IDC_GBO_CONFIG                  1012
#define IDC_STC_IPADDR                  1013
#define IDC_STC_WANIPADDR               1014
#define IDC_EDT_IPADDR                  1015
#define IDC_CBO_FEATURE_LIBKEY          1016
#define IDC_EDT_IPADDR2                 1016
#define IDC_EDT_WANIPADDR               1016
#define IDC_BTN_FEATURE_LIBKEY          1017
#define IDC_CBO_FEATURE_FACEKEY         1018
#define IDC_BTN_FEATURE_FACEKEY         1019
#define IDC_BTN_FEATURE_QUERY           1020
#define IDC_EDT_FEATURE_PICPATH         1021
#define IDC_BTN_FEATURE_PICPATH         1022
#define IDC_BTN_FEATURE_CALC            1023
#define IDC_STC_FEATURE_LIBKEY          1024
#define IDC_STC_FEATURE_FACEKEY         1025
#define IDC_STC_FEATURE_PICPATH         1026
#define IDC_CBO_ALARM_LIBKEY            1027
#define IDC_BUTTON1                     1028
#define IDC_BTN_ALARM_LIBKEY            1028
#define IDC_BTN_LIBKEY_QUERY            1028
#define IDC_BTN_ADV_LIBKEY_QUERY        1028
#define IDC_BTN_LIB_QUERY               1028
#define IDC_BTN_STREAM_SRART            1028
#define IDC_BTN_PIC_PATH                1028
#define IDC_BTN_SEARCH_PATH             1028
#define IDC_BUTTON_QUERY                1028
#define IDC_BTN_FACE_LIB_EDIT_CONFIRM   1028
#define IDC_BUTTON_SET                  1028
#define IDC_BTN_LIB_DELT_SYNC_LIB       1028
#define IDC_BTN_LIB_MODIFY_IPC          1028
#define IDC_EDT_ALARM_INTERVAL          1029
#define IDC_BTN_LIB_ADD                 1029
#define IDC_BTN_PIC_LIBKEY_QUERY        1029
#define IDC_BTN_SEARCH_LIB              1029
#define IDC_BUTTON_RESULT               1029
#define IDC_BTN_FACE_LIB_EDIT_CANCLE    1029
#define IDC_CBO_ALARM_TYPE              1030
#define IDC_BTN_LIB_MODIFY              1030
#define IDC_BUTTON_PROCESS              1030
#define IDC_CBO_ALARM_VCA_TYPE          1031
#define IDC_CBO_LIBKEY                  1031
#define IDC_BTN_LIB_DELETE              1031
#define IDC_CBO_ALARM_RECOGNISE         1032
#define IDC_CBO_ALARM_DEVTYPE           1033
#define IDC_B                           1034
#define IDC_BTN_ALARM_SET               1034
#define IDC_BTN_ALARM_GET               1035
#define IDC_EDT_ALARM_FREQ              1036
#define IDC_EDT_ALARM_SIMILAR           1037
#define IDC_BTN_ALARMLINK_LIBKEY        1041
#define IDC_CBO_SCHE                    1042
#define IDC_CHK_SCHE                    1043
#define IDC_CHK_TIME1                   1044
#define IDC_CHK_TIME2                   1045
#define IDC_CHK_TIME3                   1046
#define IDC_CHK_TIME4                   1047
#define IDC_DATE_BEG1                   1048
#define IDC_DATE_BEG2                   1049
#define IDC_DATE_BEG3                   1050
#define IDC_DATE_BEG4                   1051
#define IDC_BTN_SET                     1052
#define IDC_DATE_END1                   1053
#define IDC_CHK_ALARM_ENABLE            1053
#define IDC_DATE_END2                   1054
#define IDC_DATE_END3                   1055
#define IDC_EDT_ADV_FILEPATH            1055
#define IDC_DATE_END4                   1056
#define IDC_BTN_ADV_FILE_PATH           1056
#define IDC_BTN_GET                     1057
#define IDC_BTN_ADV_IMPORT              1057
#define IDC_BTN_ADV_EXPOR               1058
#define IDC_CBO_ADV_LIBKEY              1059
#define IDC_STC_ADV_EXPORT_PROCESS      1060
#define IDC_EDT_LIB_NAME                1061
#define IDC_EDT_LIB_UUID                1062
#define IDC_EDT_LIB_VERSION             1063
#define IDC_CBO_LIB_UPLOAD              1064
#define IDC_SLD_LIB_THRESHOLD           1065
#define IDC_EDT_LIB_DESCRIP             1066
#define IDC_LST_LIB_INFO                1067
#define IDC_STC_LIB_THRESHOLD           1068
#define IDC_BTN_STREAM_STOP             1069
#define IDC_STC_STREAM_FULLPIC          1070
#define IDC_STC_STREAM_SNAP1            1072
#define IDC_STC_STREAM_NEG1             1073
#define IDC_CBO_PIC_LIB                 1074
#define IDC_CBO_PIC_SEX                 1075
#define IDC_STC_STREAM_SNAP2            1076
#define IDC_CBO_PIC_NATION              1076
#define IDC_STC_STREAM_NEG2             1077
#define IDC_CBO_PIC_PROVIENCE           1077
#define IDC_STC_STREAM_SNAP3            1078
#define IDC_CBO_PIC_CITY                1078
#define IDC_STC_STREAM_NEG3             1079
#define IDC_CBO_PIC_MODEL               1079
#define IDC_CBO_PIC_CARDTYPE            1080
#define IDC_STC_STREAM_SNAP4            1080
#define IDC_EDT_PIC_CARDNUM             1081
#define IDC_STC_STREAM_NEG4             1081
#define IDC_EDT_PIC_PATH                1082
#define IDC_EDT_PIC_NAME                1083
#define IDC_EDT_PIC_UUID                1084
#define IDC_DATETIMEPICKER1             1085
#define IDC_DATETIMEPICKER2             1086
#define IDC_CBO_PIC_DST_LIB             1087
#define IDC_BTN_PIC_QUERY               1088
#define IDC_BTN_PIC_ADD                 1089
#define IDC_BTN_PIC_MODIFY              1090
#define IDC_BTN_PIC_DELETE              1091
#define IDC_LST_PIC_INFO                1092
#define IDC_GBO_PIC_MAIN                1093
#define IDC_GBO_ADVANCE_MAIN            1094
#define IDC_CBO_PIC_MODELTYPE           1094
#define IDC_GBO_ALRM_MAIN               1095
#define IDC_BTN_PIC_MODEL_START         1095
#define IDC_GBO_FEATURE_MAIN            1096
#define IDC_BTN_PIC_MODEL_STOP          1096
#define IDC_GBO_LIB_MAIN                1097
#define IDC_BTN_PIC_COPY                1097
#define IDC_GBO_SCHDULE_MAIN            1098
#define IDC_BTN_PIC_MOVE                1098
#define IDC_GBO_STREAM_MAIN             1099
#define IDC_BTN_PIC_PAGE_FIRST          1100
#define IDC_BTN_PIC_PAGE_PRE            1101
#define IDC_BTN_PIC_PAGE_NEXT           1102
#define IDC_BTN_PIC_PAGE_LAST           1103
#define IDC_CBO_PIC_PAGE                1104
#define IDC_STC_PIC_PAGE                1105
#define IDC_PROGRESS_PIC_MODEL          1109
#define IDC_STC_PIC_MODEL_PROCESS       1110
#define IDC_STC_STREAM_SIMILAR1         1111
#define IDC_STC_STREAM_SIMILAR2         1112
#define IDC_GBO_SEARCH                  1112
#define IDC_GBO_SEARCH_MAN              1112
#define IDC_EDT_SEARCH_PICPATH          1113
#define IDC_STC_STREAM_SIMILAR3         1114
#define IDC_BTN_SEARCH_CUT              1115
#define IDC_STC_STREAM_SIMILAR4         1115
#define IDC_CBO_SEARCH_CUTRET           1116
#define IDC_BTN_SEARCH_QUERY            1117
#define IDC_CBO_SEARCH_LIB              1118
#define IDC_BTN_SEARCH_SEARCH           1119
#define IDC_STC_SEARCH_PICSHOW          1120
#define IDC_LST_SEARCH_INFO             1121
#define IDC_SLIDER1                     1122
#define IDC_SLD_SEARCH_SIMILAR          1122
#define IDC_SLD_FACE_LIB_EDIT_SIMILAR   1122
#define IDC_SLIDER_ZHZL                 1122
#define IDC_STC_SEARCH_SILIMAR          1123
#define IDC_LST_LIB_SYNC_INFO           1124
#define IDC_BTN_LIB_START_SYNC          1125
#define IDC_BTN_LIB_STOP_SYNC           1126
#define IDC_BTN_LIB_DELT_SYNC           1127
#define IDC_BTN_LIB_REFESH_SYNC         1128
#define IDC_CBO_ALARMLINK_ALARM_TYPE    1129
#define IDC_CBO_ALARMLINK_LIBKEY        1130
#define IDC_CBO_ALARMLINK_VCATYPE       1131
#define IDC_BTN_ALARMLINK_SET           1134
#define IDC_BTN_ALARMLINK_GET           1135
#define IDC_EDIT_ALARMLINK_LINKTYPE     1137
#define IDC_CBO_ALARM_SCHEDULE_VCATYPE  1138
#define IDC_CHK_ALARMLINK_OUTPORT1      1139
#define IDC_CHK_ALARMLINK_OUTPORT2      1140
#define IDC_CBO_ALARMLINK_LINKTYPE      1142
#define IDC_CHECK_SYNCLIB_STATUS        1143
#define IDC_CHK_ALARM_LIB_ENABLE        1144
#define IDC_STATIC_PICTURE_PATH         1146
#define IDC_BTN_SEARCH_SNAP             1147
#define IDC_EDT_SEARCH_SNAP_PICPATH     1148
#define IDC_BTN_SEARCH_SNAP_PATH        1149
#define IDC_BTN_SEARCH_SNAP_CUT         1150
#define IDC_STC_SEARCH_SNAP_PICSHOW     1151
#define IDC_STATIC_CUT_PIC_RESULT       1152
#define IDC_CBO_SEARCH_SNAP_CUTRET      1153
#define IDC_STATIC_CUT_RESULT           1154
#define IDC_CBO_SEARCH_SNAP_SORT_MODE   1155
#define IDC_LST_ALARM_LIB               1155
#define IDC_STATIC_START_TIME           1156
#define IDC_STC_ALARM_SIMILAR           1156
#define IDC_STATIC_END_TIME             1157
#define IDC_STC_ALARM_INTERVAL          1157
#define IDC_STATIC_SIMILIRITY           1158
#define IDC_STC_ALARM_FREQ              1158
#define IDC_SLD_SEARCH_SNAP_SIMILAR     1159
#define IDC_STC_LIB_SPCOUNT             1159
#define IDC_LST_SEARCH_SNAP_INFO        1160
#define IDC_STC_PIC_SPCOUNT             1160
#define IDC_STATIC_SORT_MODE            1161
#define IDC_EDT_FACE_LIB_NAME           1162
#define IDC_DATETIMEPICKER_BEGIN        1163
#define IDC_EDT_FACE_LIB_DESCRIP        1163
#define IDC_DATETIMEPICKER_END          1164
#define IDC_STC_FACE_LIB_EDIT_SIMILAR   1164
#define IDC_STATIC_CHAN_CHOSE           1165
#define IDC_CHECK_CHAN_ALL              1166
#define IDC_CHECK_CHAN_1                1167
#define IDC_CHECK_CHAN_2                1168
#define IDC_CHECK_CHAN_3                1169
#define IDC_CHECK_CHAN_4                1170
#define IDC_CHECK_CHAN_5                1171
#define IDC_CHECK_CHAN_6                1172
#define IDC_CHECK_CHAN_7                1173
#define IDC_CHECK_CHAN_8                1174
#define IDC_CHECK_CHAN_9                1175
#define IDC_CHECK_CHAN_10               1176
#define IDC_CHECK_CHAN_11               1177
#define IDC_CHECK_CHAN_12               1178
#define IDC_CHECK_CHAN_13               1179
#define IDC_CHECK_CHAN_14               1180
#define IDC_CHECK_CHAN_15               1181
#define IDC_CHECK_CHAN_16               1182
#define IDC_CHECK_CHAN_17               1183
#define IDC_CHECK_CHAN_18               1184
#define IDC_CHECK_CHAN_19               1185
#define IDC_CHECK_CHAN_20               1186
#define IDC_CHECK_CHAN_21               1187
#define IDC_CHECK_CHAN_22               1188
#define IDC_CHECK_CHAN_23               1189
#define IDC_CHECK_CHAN_24               1190
#define IDC_CHECK_CHAN_25               1191
#define IDC_CHECK_CHAN_26               1192
#define IDC_CHECK_CHAN_27               1193
#define IDC_CHECK_CHAN_28               1194
#define IDC_CHECK_CHAN_29               1195
#define IDC_CHECK_CHAN_30               1196
#define IDC_CHECK_CHAN_31               1197
#define IDC_CHECK_CHAN_32               1198
#define IDC_STATIC_SIMILARITY           1199
#define IDC_STATIC_PROCESS              1200
#define IDC_BTN_PIC_INPORT              1201
#define IDC_BTN_PIC_OUTPORT_ALL         1202
#define IDC_PROGRESS_EXPORT             1203
#define IDC_STC_EXPORT_RESULT           1204
#define IDC_STC_EXPORT_PROCESS          1205
#define IDC_STC_DL_STATE                1206
#define IDC_STC_DL_STATE_SNAP           1207
#define IDC_EDT_PICEDIT_NAME            1208
#define IDC_DT_PICEDIT_BIRTH            1209
#define IDC_STC_PICEDIT_PIC             1210
#define IDC_BTN_PICEDIT_UPLOAD          1211
#define IDC_BTN_PICEDIT_OK              1212
#define IDC_BTN_PICEDIT_CANCEL          1213
#define IDC_EDT_PICEDIT_CARDNUM         1214
#define IDC_CBO_PICEDIT_CARDTYPE        1215
#define IDC_CBO_PICEDIT_SEX             1216
#define IDC_CBO_PICEDIT_NATION          1217
#define IDC_CBO_PICEDIT_PROVIENCE       1218
#define IDC_CBO_PICEDIT_CITY            1219
#define IDC_STC_ALARM_SIMILAR_VALUE     1220
#define IDC_CHK_ALARM_TYPE_ENABLE       1221
#define IDC_SLD_ALARM_SIMILAR           1222
#define IDC_CHECK_ENABLE_FACE_DETECT    1223
#define IDC_COMBO_TTCL                  1224
#define IDC_COMBO_ZPCS                  1225
#define IDC_COMBO_ZPMS                  1226
#define IDC_EDIT_ZXRLCC                 1227
#define IDC_STATIC_TTCL                 1228
#define IDC_STATIC_ZPCS                 1229
#define IDC_STATIC_ZPMS                 1230
#define IDC_STATIC_ZHZL                 1231
#define IDC_STATIC_ZXRLCC               1232
#define IDC_STATIC_ZHZL_VALUE           1233
#define IDC_STATIC_FACE_DETECT_STATE    1234
#define IDC_COMBO_FACE_DETECT_STATE     1235
#define IDC_SLIDER_RLBGLD               1236
#define IDC_STATIC_RLBGLD               1237
#define IDC_STATIC_RLBGLD_VALUE         1238
#define IDC_CHECK_DETECT_SHOWRULE       1239
#define IDC_CHECK_DETECT_SHOWTARGET     1240
#define IDC_SLIDER_ZPJG                 1241
#define IDC_STATIC_ZPJG                 1242
#define IDC_STATIC_ZPJG_VALUE           1243
#define IDC_SLIDER_FACEDETECT_BIGPIC    1244
#define IDC_SLIDER_FACEDETECT_SMALLPIC  1245
#define IDC_STATIC_FACEDETECT_BIGPIC    1246
#define IDC_STATIC_FACEDETECT_SMALLPIC  1247
#define IDC_STATIC_FACEDETECT_BIGPIC_VALUE 1248
#define IDC_STATIC_FACEDETECT_SMALLPIC_VALUE 1249
#define IDC_CHECK_FACEDETECT_SNAPBIGPIC 1250
#define IDC_CHECK4                      1251
#define IDC_CHECK_FACEDETECT_BIGPICOSD  1251
#define IDC_STATIC_WAN_PORT             1252
#define IDC_EDIT_LAN_PORT               1253
#define IDC_EDIT_WAN_PORT               1253
#define IDC_RADIO_NORMAL_MODE           1254
#define IDC_RADIO_ACTIVE_MODE           1255
#define IDC_STATIC_LOGON_MODE           1256
#define IDC_EDIT_COMPANY                1257
#define IDC_EDIT_ADDRESS                1258
#define IDC_STATIC_COMPANY              1259
#define IDC_STATIC_ADDRESS              1260
#define IDC_COMBO_COUNTRY               1261
#define IDC_STATIC_COUNTRY              1262
#define IDC_COMBO1_COUNTRY              1263
#define IDC_EDIT1                       1264
#define IDC_EDIT1_COMPANY               1264
#define IDC_EDIT_FREQ_GROUP             1264
#define IDC_EDIT_FACE_LIB_UUID          1264
#define IDC_EDIT2                       1266
#define IDC_STATIC1_COMAPNY             1267
#define IDC_STATIC1_ADDRESS             1268
#define IDC_CBO_SYNC_LIB_KEY            1272
#define IDC_BUTTON4                     1273
#define IDC_STATIC_SYNC_INFO            1274
#define IDC_STATIC_SYNC_FAIL_INFO       1275
#define IDC_BTN_LIB_CLEAR_FAIL_INFO     1276
#define IDC_EDIT_SYNC_RESULT            1277
#define IDC_BUTTON_LIB_CLEAR            1278
#define IDC_EDIT_PIC_SCORELEVEL         1279
#define IDC_EDIT_SCORELEVEL             1281
#define IDC_EDIT_SCORE                  1282
#define IDC_EDIT_FREQ                   1283
#define IDC_EDIT_FREQ_CHAN              1283
#define IDC_STATIC_ALARM_INTERVAL_UINT  1284
#define IDC_STC_FREQ_GROUP              1285
#define IDC_STC_FREQ_CHAN               1286
#define IDC_COMBO1                      1287
#define IDC_COMBO_FREQ_GROUP            1288
#define IDC_STATIC_FACE_LIB_UUID        1289
#define IDC_BTN_LIB_START_SYNC_ADDTO    1290

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1291
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
