//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VideoDisplay.rc
//
#define ID_TIMER_FILE_DOWNLOAD_POS      1
#define ID_TIMER_TIME_DOWNLOAD_POS      2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VIDEODISPLAY_DIALOG         102
#define IDD_MAIN_DIALOG                 103
#define IDR_MAINFRAME                   128
#define IDD_FILE_DISPLAY_DIALOG         129
#define IDD_TIME_DISPLAYDIALOG          130
#define IDD_DISPLAY_DIALOG              133
#define IDC_EDIT_DEVICE_IP              1001
#define IDC_EDIT_DEVICE_IP2             1002
#define IDC_EDIT_PORT_INPUT             1002
#define IDC_EDIT_DEVICE_IP3             1003
#define IDC_BUTTON1                     1004
#define IDC_BUTTON_QUERY                1004
#define IDC_BUTTON_SET_LANGUAGE         1004
#define IDC_BUTTON_                     1004
#define IDC_BUTTON_VOLUME_CTRL          1004
#define IDC_EDIT_DEVICE_IP4             1005
#define IDC_BUTTON5                     1005
#define IDC_EDIT_PASSWORD               1005
#define IDC_BUTTON_TIME_MODE_DOWNLOAD   1005
#define IDC_BUTTON_CAPTURE              1005
#define IDC_BUTTON2                     1006
#define IDC_BUTTON_TIME_MODE_SET_DOWN_LAOD_SPEED 1006
#define IDC_BUTTON3                     1007
#define IDC_EDIT_DEVICE_IP5             1007
#define IDC_FILE_MODE_DOWNLOAD_POS      1007
#define IDC_BUTTON_LOGOFF               1007
#define IDC_BUTTON4                     1008
#define IDC_BUTTON_TIME_MODE_PLAY       1008
#define IDC_BUTTON_FORWARD_STEP         1008
#define IDC_BUTTON6                     1009
#define IDC_COMBO1                      1010
#define IDC_COMBO_TIME_MODE_CHANNEL_NUM 1010
#define IDC_COMBO2                      1011
#define IDC_BUTTON7                     1011
#define IDC_COMBO_FILE_MODE_FILE_TYPE   1011
#define IDC_BUTTON_TIME_MODE_STOP_DOWNLAOD 1011
#define IDC_IPADDRESS1                  1012
#define IDC_COMBO4                      1012
#define IDC_COMBO_TIME_MODE_DOWNLOAD_SPEED 1012
#define IDC_DATETIMEPICKER1             1013
#define IDC_DATETIMEPICKER2             1014
#define IDC_DATETIMEPICKER3             1015
#define IDC_LIST3                       1022
#define IDC_PROGRESS1                   1023
#define IDC_BUTTON_LOGON                1026
#define IDC_BUTTON_START_DISPLAY        1027
#define IDC_STATIC_DISPLAY              1028
#define IDC_STATIC_DISPLAY_SPEED        1029
#define IDC_STATIC_FAST_PLAY            1029
#define IDC_COMBO_DISPLAY_SPEED         1030
#define IDC_BUTTON_STOP_DISPLAY         1031
#define IDC_EDIT_USERNAME               1032
#define IDC_STATIC_DISPLAY_SPEED2       1032
#define IDC_STATIC_PLAY_POS             1032
#define IDC_EDIT_USERNAME2              1033
#define IDC_EDIT_IP_ADRESS              1033
#define IDC_BUTTON_START_DISPLAY2       1033
#define IDC_BUTTON_FAST_PLAY            1033
#define IDC_LIST_LOG                    1034
#define IDC_BUTTON_START_DISPLAY3       1034
#define IDC_BUTTON_POS_SET              1034
#define IDC_STATIC_CHILD_AREA           1035
#define IDC_STATIC_DISPLAY_SPEED3       1035
#define IDC_STATIC_SLOW_PLAY            1035
#define IDC_DATETIMEPICKER_FILE_MODE_START_TIME 1036
#define IDC_COMBO_DISPLAY_SPEED2        1036
#define IDC_DATETIMEPICKER_FILE_MODE_STOP_TIME 1037
#define IDC_BUTTON_START_DISPLAY4       1037
#define IDC_BUTTON_SLOW_SET             1037
#define IDC_COMBO_FILE_MODE_CHANNEL     1039
#define IDC_FILE_MODE_DOWNLOAD_SPEED    1040
#define IDC_COMBO_FILE_MODE_CHANNEL2    1040
#define IDC_BUTTON_DOWNLOAD             1041
#define IDC_BUTTON_PLAY                 1042
#define IDC_BUTTON_DOWNLOAD_SPEED       1043
#define IDC_BUTTON_DOWNLOAD_POS         1044
#define IDC_BUTTON_STOP_DOWNLOAD        1045
#define IDC_BUTTON_PAUSE                1046
#define IDC_BUTTON_CONTINUE_DOWNLOAD    1047
#define IDC_LIST1                       1048
#define IDC_COMBO_FILE_MODE_SREAM       1048
#define IDC_PROGRESS2                   1049
#define IDC_COMBO_FILE_SAVEFILE_TYPE    1049
#define IDC_EDIT1                       1050
#define IDC_COMBO3                      1051
#define IDC_COMBO_TIME_MODE_STREAM_TYPE 1051
#define IDC_COMBO_LANGUAGE              1054
#define IDC_TAB_LANGUAGE                1055
#define IDC_TREE1                       1056
#define IDC_STATIC_PORT                 1057
#define IDC_STATIC_USERNAME             1058
#define IDC_STATIC_PASSWORD             1059
#define IDC_BUTTON_FILE                 1060
#define IDC_BUTTON_TIME_SPACE           1061
#define IDC_STATIC_FILE_MODE_TIMESPACE  1062
#define IDC_STATIC_FILE_MODE_TO         1063
#define IDC_STATIC_FILE_MODE_CHANNEL_NUM 1064
#define IDC_STATIC_FILE_MODE_FILE_TYPE  1065
#define IDC_STATIC_FILE_MODE_DOWNLOAD_SPEED 1066
#define IDC_STATIC_FILE_MODE_DOWNLOAD_POS 1067
#define IDC_STATIC_TIME_MODE_TIME_SPACE 1068
#define IDC_STATIC_TIME_MODE_CHANNEL_NUM 1069
#define IDC_STATIC_TIME_MODE_TO         1070
#define IDC_STATIC_TIME_MODE_DWONLOAD_SPEED 1071
#define IDC_STATIC_TIME_MODE_DOWNLAOD_POS 1072
#define IDC_SLIDER_VOICE_CTRL           1073
#define IDC_STATIC_VOLUME               1074
#define IDC_BUTTON_PAUSE_PLAY           1075
#define IDC_STATIC_VOLUME_DISPLAY       1076
#define IDC_STATIC_PROCESS              1077
#define ID_SNATCH_BMP                   1078
#define IDC_COMBO_STREAM_SAVEFILE_TYPE  1078
#define ID_SNATCH_JPG                   1079
#define IDC_STATIC_STREAM_TYPE          1079
#define IDC_COMBO_FILE_PAGE             1080

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
