INSERT INTO system_dict_data(sort,label,value,dict_type,status,remark,creator,updater) VALUES
(1,'摄像机','CAM','ibms_device_type',0,'{"desc": "视频采集设备、车辆识别一体机", "parent": "视频监控、停车场、门禁系统、智能对讲"}','excel_v22','excel_v22'),
(2,'读卡器','READER','ibms_device_type',0,'{"desc": "门禁读卡设备", "parent": "门禁系统、可视对讲"}','excel_v22','excel_v22'),
(3,'传感器','SENSOR','ibms_device_type',0,'{"desc": "环境传感器", "parent": "楼宇自控、环境监测、智能照明、门禁系统、停车场"}','excel_v22','excel_v22'),
(4,'控制器','CONTR','ibms_device_type',0,'{"desc": "通用控制器", "parent": "楼宇自控、智能照明、门禁系统、入侵报警、车辆管理、环境监测、能源管理、智能对讲、电梯控制、火灾报警"}','excel_v22','excel_v22'),
(5,'DDC控制器','DDC','ibms_device_type',0,'{"desc": "可编程控制器", "parent": "楼宇自控"}','excel_v22','excel_v22'),
(6,'服务器','SERVER','ibms_device_type',0,'{"desc": "平台服务器、存储服务器硬件", "parent": "视频监控、入侵报警、停车场、门禁系统、访客系统、环境监测、智能照明、楼宇自控、智能对讲"}','excel_v22','excel_v22'),
(7,'网络录像机','NVR','ibms_device_type',0,'{"desc": "视频存储设备", "parent": "视频监控"}','excel_v22','excel_v22'),
(8,'探测器','DETECTOR','ibms_device_type',0,'{"desc": "报警探测器", "parent": "入侵报警"}','excel_v22','excel_v22'),
(9,'调光驱动','DRIVER','ibms_device_type',0,'{"desc": "LED调光驱动", "parent": "智能照明"}','excel_v22','excel_v22'),
(10,'仪表','METER','ibms_device_type',0,'{"desc": "电表/水表", "parent": "能源管理、变配电"}','excel_v22','excel_v22'),
(11,'功放','AMPLIFIER','ibms_device_type',0,'{"desc": "广播功放", "parent": "公共广播"}','excel_v22','excel_v22'),
(12,'车辆道闸','BOOM','ibms_device_type',0,'{"desc": "车辆闸机设备", "parent": "停车场"}','excel_v22','excel_v22'),
(13,'访客主机','VISITOR','ibms_device_type',0,'{"desc": "访客设备", "parent": "访客系统"}','excel_v22','excel_v22');
