INSERT INTO system_dict_data(sort,label,value,dict_type,status,remark,creator,updater) VALUES
(1,'视频通道','VT','ibms_point_type',0,'{"dataType": "视频流", "systems": ["VI"], "deviceTypes": ["CAM", "NVR"], "desc": "主码流视频通道，用于实时监控和录像存储，分辨率通常为1080P/4K"}','excel_v22','excel_v22'),
(2,'子码流','VT-Sub','ibms_point_type',0,'{"dataType": "视频流", "systems": ["VI"], "deviceTypes": ["CAM"], "desc": "辅码流/三码流，用于手机预览或网络带宽受限场景，分辨率通常为720P/D1/CIF"}','excel_v22','excel_v22'),
(3,'视频输入','VT-In','ibms_point_type',0,'{"dataType": "视频流", "systems": ["VI"], "deviceTypes": ["NVR"], "desc": "NVR视频输入通道，接入前端摄像机码流，支持16-256路接入"}','excel_v22','excel_v22'),
(4,'视频输出','VT-Out','ibms_point_type',0,'{"dataType": "视频流", "systems": ["VI"], "deviceTypes": ["NVR"], "desc": "NVR本地视频输出通道，HDMI/VGA接口连接监视器，支持1-4路分屏显示"}','excel_v22','excel_v22'),
(5,'报警输入','AI','ibms_point_type',0,'{"dataType": "DI", "systems": ["AL"], "deviceTypes": ["CONTR", "SENSOR"], "desc": "防区报警输入通道，1个物理接入点=1个防区=1个AI通道，支持常开/常闭/线尾电阻模式，可串联多个探测器"}','excel_v22','excel_v22'),
(6,'报警输出','AO','ibms_point_type',0,'{"dataType": "DO", "systems": ["AL"], "deviceTypes": ["CONTR"], "desc": "报警联动输出通道，继电器干接点输出，用于联动警号、灯光、视频等，支持常开/常闭"}','excel_v22','excel_v22'),
(7,'门禁点','DR','ibms_point_type',0,'{"dataType": "逻辑点", "systems": ["AC"], "deviceTypes": ["CONTR"], "desc": "完整门禁控制点，1扇门对应1个DR，包含读卡器输入、电锁控制、门磁反馈、按钮输入的逻辑组合"}','excel_v22','excel_v22'),
(8,'读卡输入','DR-Reader','ibms_point_type',0,'{"dataType": "DI", "systems": [], "deviceTypes": ["READER", "VISITOR"], "desc": "读卡器输入通道，支持IC卡/CPU卡/指纹/人脸/二维码/蓝牙/NFC等多种识别方式"}','excel_v22','excel_v22'),
(9,'数字输入','DI','ibms_point_type',0,'{"dataType": "DI", "systems": [], "deviceTypes": ["CONTR", "DDC", "SENSOR", "BOOM"], "desc": "数字量输入通道，采集开关状态信号，如设备运行/停止、故障/正常、手动/自动等状态"}','excel_v22','excel_v22'),
(10,'数字输出','DO','ibms_point_type',0,'{"dataType": "DO", "systems": [], "deviceTypes": ["CONTR", "DDC", "BOOM", "VISITOR"], "desc": "数字量输出通道，输出开关控制信号，如设备启停、阀门开关、继电器动作等"}','excel_v22','excel_v22'),
(11,'模拟输入','AI\\_AN','ibms_point_type',0,'{"dataType": "AI", "systems": [], "deviceTypes": ["CONTR", "DDC", "SENSOR"], "desc": "模拟量输入通道，采集连续变化信号，支持4-20mA/0-10V/0-5V/热电阻/热电偶等标准信号"}','excel_v22','excel_v22'),
(12,'模拟输出','AO\\_AN','ibms_point_type',0,'{"dataType": "AO", "systems": [], "deviceTypes": ["CONTR", "DDC"], "desc": "模拟量输出通道，输出连续控制信号，支持4-20mA/0-10V标准信号，用于阀门开度、变频频率等调节"}','excel_v22','excel_v22'),
(13,'对讲终端','IT','ibms_point_type',0,'{"dataType": "音视频", "systems": [], "deviceTypes": ["READER", "VISITOR"], "desc": "音视频对讲通道，支持双向语音通话和视频传输，用于门口机与室内机/管理中心通信"}','excel_v22','excel_v22'),
(14,'消防点位','FP','ibms_point_type',0,'{"dataType": "DI/DO", "systems": ["FD"], "deviceTypes": ["CONTR"], "desc": "消防点位通道，包含火警探测器输入、故障反馈、手动报警按钮、控制模块输出等，支持回路编址"}','excel_v22','excel_v22'),
(15,'照明回路','LT','ibms_point_type',0,'{"dataType": "DO/AO", "systems": ["LI"], "deviceTypes": ["CONTR", "DRIVER"], "desc": "照明控制回路，支持开关控制和调光控制两种模式，可配置为DO开关或AO调光"}','excel_v22','excel_v22'),
(16,'调光回路','LT-Dim','ibms_point_type',0,'{"dataType": "AO", "systems": ["LI"], "deviceTypes": ["DRIVER"], "desc": "调光控制回路，支持0-10V模拟调光、DALI数字调光、PWM调光、可控硅相位调光等方式"}','excel_v22','excel_v22'),
(17,'开关回路','LT-Switch','ibms_point_type',0,'{"dataType": "DO", "systems": ["LI"], "deviceTypes": ["DRIVER"], "desc": "开关控制回路，继电器干接点输出，控制灯具启停，支持常开/常闭触点"}','excel_v22','excel_v22'),
(18,'电能监测','PM','ibms_point_type',0,'{"dataType": "AI", "systems": [], "deviceTypes": ["METER", "CONTR"], "desc": "电能监测通道，采集电压、电流、功率、功率因数、频率、电能等参数，支持三相/单相计量"}','excel_v22','excel_v22'),
(19,'电梯通道','EC','ibms_point_type',0,'{"dataType": "DI/AI", "systems": ["EL"], "deviceTypes": ["CONTR"], "desc": "电梯状态监测通道，采集电梯运行方向、当前楼层、门区信号、故障报警等状态，支持BCD/格雷码/通讯方式"}','excel_v22','excel_v22'),
(20,'广播通道','BC','ibms_point_type',0,'{"dataType": "音频", "systems": ["PA"], "deviceTypes": ["AMPLIFIER"], "desc": "广播音频输出通道，支持定压（70V/100V）或定阻输出，功率范围10W-2000W，可分区控制"}','excel_v22','excel_v22'),
(21,'巡更点','GP','ibms_point_type',0,'{"dataType": "DI", "systems": [], "deviceTypes": ["-"], "desc": "巡更签到点通道，采集巡更棒/刷卡/指纹等签到信息，记录巡更时间地点（系统预留）"}','excel_v22','excel_v22'),
(22,'停车场点','CP','ibms_point_type',0,'{"dataType": "DI/DO/AI", "systems": ["CA"], "deviceTypes": ["CONTR"], "desc": "停车场综合控制点，包含车道检测、道闸控制、车位引导、收费管理等功能的组合"}','excel_v22','excel_v22'),
(23,'道闸控制','CP-Gate','ibms_point_type',0,'{"dataType": "DO/DI", "systems": ["CA"], "deviceTypes": ["BOOM"], "desc": "道闸控制通道，DO输出控制道闸升/降/停，DI输入检测道闸开到位/关到位/过车线圈"}','excel_v22','excel_v22'),
(24,'地感输入','CP-Loop','ibms_point_type',0,'{"dataType": "DI", "systems": ["CA"], "deviceTypes": ["BOOM"], "desc": "地感线圈检测输入通道，检测车辆 presence，用于触发抓拍、防砸车、车流量统计"}','excel_v22','excel_v22'),
(25,'软件通道','虚拟','ibms_point_type',0,'{"dataType": "数据", "systems": [], "deviceTypes": ["SERVER"], "desc": "软件服务虚拟通道，用于数据管理、策略运算、网络服务、系统集成等无物理IO的功能"}','excel_v22','excel_v22');
