//------------------------------------------------------------------------------
// <auto-generated>
// This code is generated by the tool.
// Runtime library version: 2.0.50727.8689
//
// Changes to this file may cause incorrect behavior, and if
// Regenerate the code, these changes will be lost.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSDKDemo.Properties
{


    /// <summary>
     /// A strongly typed resource class for finding localized strings, etc.
    /// </summary>
     // This class is created by StronglyTypedResourceBuilder
     // Classes are automatically generated by tools like ResGen or Visual Studio.
     // To add or remove members, edit the .ResX file and rerun ResGen
     // (with /str as a command option), or rebuild the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
         /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetSDKDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
         /// Override the CurrentUICulture property of the current thread for all resource lookups,
         /// The way is to use this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
